/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/CallingSettings_calling_sip.h"

namespace onemsg {
namespace sdk {
namespace model {

CallingSettings_calling_sip::CallingSettings_calling_sip()
{
    m_StatusIsSet = false;
    m_ServersIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

CallingSettings_calling_sip::~CallingSettings_calling_sip()
{
}

void CallingSettings_calling_sip::validate()
{
    // TODO: implement validation
}

web::json::value CallingSettings_calling_sip::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }
    if(m_ServersIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("servers"))] = ModelBase::toJson(m_Servers);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool CallingSettings_calling_sip::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("servers"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("servers")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<CallingSettings_calling_sip_servers_inner>> refVal_setServers;
            ok &= ModelBase::fromJson(fieldValue, refVal_setServers);
            setServers(refVal_setServers);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("status"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("servers"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void CallingSettings_calling_sip::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
    if(m_ServersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("servers")), m_Servers));
    }
}

bool CallingSettings_calling_sip::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("servers"))))
    {
        std::vector<std::shared_ptr<CallingSettings_calling_sip_servers_inner>> refVal_setServers;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("servers"))), refVal_setServers );
        setServers(refVal_setServers);
    }
    return ok;
}

CallingSettings_calling_sip::StatusEnum CallingSettings_calling_sip::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("ENABLED")) {
        return StatusEnum::ENABLED;
    }
    
    if (value == utility::conversions::to_string_t("DISABLED")) {
        return StatusEnum::DISABLED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t CallingSettings_calling_sip::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::ENABLED: return utility::conversions::to_string_t("ENABLED");
        
        case StatusEnum::DISABLED: return utility::conversions::to_string_t("DISABLED");
        
    }
}


CallingSettings_calling_sip::StatusEnum CallingSettings_calling_sip::getStatus() const
{
    return m_Status;
}


void CallingSettings_calling_sip::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool CallingSettings_calling_sip::statusIsSet() const
{
    return m_StatusIsSet;
}

void CallingSettings_calling_sip::unsetStatus()
{
    m_StatusIsSet = false;
}
std::vector<std::shared_ptr<CallingSettings_calling_sip_servers_inner>> CallingSettings_calling_sip::getServers() const
{
    return m_Servers;
}


void CallingSettings_calling_sip::setServers(const std::vector<std::shared_ptr<CallingSettings_calling_sip_servers_inner>>& value)
{
    m_Servers = value;
    m_ServersIsSet = true;
}

bool CallingSettings_calling_sip::serversIsSet() const
{
    return m_ServersIsSet;
}

void CallingSettings_calling_sip::unsetServers()
{
    m_ServersIsSet = false;
}


std::map<utility::string_t, web::json::value> CallingSettings_calling_sip::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void CallingSettings_calling_sip::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void CallingSettings_calling_sip::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool CallingSettings_calling_sip::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void CallingSettings_calling_sip::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


