/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/ConversationalAutomation_commands_inner.h"

namespace onemsg {
namespace chat {
namespace model {

ConversationalAutomation_commands_inner::ConversationalAutomation_commands_inner()
{
    m_Command_name = utility::conversions::to_string_t("");
    m_Command_nameIsSet = false;
    m_Command_description = utility::conversions::to_string_t("");
    m_Command_descriptionIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

ConversationalAutomation_commands_inner::~ConversationalAutomation_commands_inner()
{
}

void ConversationalAutomation_commands_inner::validate()
{
    // TODO: implement validation
}

web::json::value ConversationalAutomation_commands_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Command_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("command_name"))] = ModelBase::toJson(m_Command_name);
    }
    if(m_Command_descriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("command_description"))] = ModelBase::toJson(m_Command_description);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool ConversationalAutomation_commands_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("command_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("command_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCommandName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCommandName);
            setCommandName(refVal_setCommandName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("command_description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("command_description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCommandDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCommandDescription);
            setCommandDescription(refVal_setCommandDescription);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("command_name"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("command_description"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void ConversationalAutomation_commands_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Command_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("command_name")), m_Command_name));
    }
    if(m_Command_descriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("command_description")), m_Command_description));
    }
}

bool ConversationalAutomation_commands_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("command_name"))))
    {
        utility::string_t refVal_setCommandName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("command_name"))), refVal_setCommandName );
        setCommandName(refVal_setCommandName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("command_description"))))
    {
        utility::string_t refVal_setCommandDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("command_description"))), refVal_setCommandDescription );
        setCommandDescription(refVal_setCommandDescription);
    }
    return ok;
}


utility::string_t ConversationalAutomation_commands_inner::getCommandName() const
{
    return m_Command_name;
}


void ConversationalAutomation_commands_inner::setCommandName(const utility::string_t& value)
{
    m_Command_name = value;
    m_Command_nameIsSet = true;
}

bool ConversationalAutomation_commands_inner::commandNameIsSet() const
{
    return m_Command_nameIsSet;
}

void ConversationalAutomation_commands_inner::unsetCommand_name()
{
    m_Command_nameIsSet = false;
}
utility::string_t ConversationalAutomation_commands_inner::getCommandDescription() const
{
    return m_Command_description;
}


void ConversationalAutomation_commands_inner::setCommandDescription(const utility::string_t& value)
{
    m_Command_description = value;
    m_Command_descriptionIsSet = true;
}

bool ConversationalAutomation_commands_inner::commandDescriptionIsSet() const
{
    return m_Command_descriptionIsSet;
}

void ConversationalAutomation_commands_inner::unsetCommand_description()
{
    m_Command_descriptionIsSet = false;
}


std::map<utility::string_t, web::json::value> ConversationalAutomation_commands_inner::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void ConversationalAutomation_commands_inner::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void ConversationalAutomation_commands_inner::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool ConversationalAutomation_commands_inner::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void ConversationalAutomation_commands_inner::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


