/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/CreateCommerce_request.h"

namespace onemsg {
namespace sdk {
namespace model {

CreateCommerce_request::CreateCommerce_request()
{
    m_ParamsIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

CreateCommerce_request::~CreateCommerce_request()
{
}

void CreateCommerce_request::validate()
{
    // TODO: implement validation
}

web::json::value CreateCommerce_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ParamsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("params"))] = ModelBase::toJson(m_Params);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool CreateCommerce_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("params"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("params")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<CreateCommerce_request_params> refVal_setParams;
            ok &= ModelBase::fromJson(fieldValue, refVal_setParams);
            setParams(refVal_setParams);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("params"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void CreateCommerce_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ParamsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("params")), m_Params));
    }
}

bool CreateCommerce_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("params"))))
    {
        std::shared_ptr<CreateCommerce_request_params> refVal_setParams;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("params"))), refVal_setParams );
        setParams(refVal_setParams);
    }
    return ok;
}


std::shared_ptr<CreateCommerce_request_params> CreateCommerce_request::getParams() const
{
    return m_Params;
}


void CreateCommerce_request::setParams(const std::shared_ptr<CreateCommerce_request_params>& value)
{
    m_Params = value;
    m_ParamsIsSet = true;
}

bool CreateCommerce_request::paramsIsSet() const
{
    return m_ParamsIsSet;
}

void CreateCommerce_request::unsetParams()
{
    m_ParamsIsSet = false;
}


std::map<utility::string_t, web::json::value> CreateCommerce_request::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void CreateCommerce_request::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void CreateCommerce_request::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool CreateCommerce_request::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void CreateCommerce_request::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


