/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/GetCommerce_200_response_inner.h"

namespace onemsg {
namespace sdk {
namespace model {

GetCommerce_200_response_inner::GetCommerce_200_response_inner()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Is_cart_enabled = false;
    m_Is_cart_enabledIsSet = false;
    m_Is_catalog_visible = false;
    m_Is_catalog_visibleIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

GetCommerce_200_response_inner::~GetCommerce_200_response_inner()
{
}

void GetCommerce_200_response_inner::validate()
{
    // TODO: implement validation
}

web::json::value GetCommerce_200_response_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Is_cart_enabledIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_cart_enabled"))] = ModelBase::toJson(m_Is_cart_enabled);
    }
    if(m_Is_catalog_visibleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_catalog_visible"))] = ModelBase::toJson(m_Is_catalog_visible);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool GetCommerce_200_response_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_cart_enabled"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_cart_enabled")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsCartEnabled;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsCartEnabled);
            setIsCartEnabled(refVal_setIsCartEnabled);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_catalog_visible"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_catalog_visible")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsCatalogVisible;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsCatalogVisible);
            setIsCatalogVisible(refVal_setIsCatalogVisible);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("id"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("is_cart_enabled"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("is_catalog_visible"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void GetCommerce_200_response_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Is_cart_enabledIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_cart_enabled")), m_Is_cart_enabled));
    }
    if(m_Is_catalog_visibleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_catalog_visible")), m_Is_catalog_visible));
    }
}

bool GetCommerce_200_response_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_cart_enabled"))))
    {
        bool refVal_setIsCartEnabled;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_cart_enabled"))), refVal_setIsCartEnabled );
        setIsCartEnabled(refVal_setIsCartEnabled);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_catalog_visible"))))
    {
        bool refVal_setIsCatalogVisible;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_catalog_visible"))), refVal_setIsCatalogVisible );
        setIsCatalogVisible(refVal_setIsCatalogVisible);
    }
    return ok;
}


utility::string_t GetCommerce_200_response_inner::getId() const
{
    return m_Id;
}


void GetCommerce_200_response_inner::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool GetCommerce_200_response_inner::idIsSet() const
{
    return m_IdIsSet;
}

void GetCommerce_200_response_inner::unsetId()
{
    m_IdIsSet = false;
}
bool GetCommerce_200_response_inner::isIsCartEnabled() const
{
    return m_Is_cart_enabled;
}

void GetCommerce_200_response_inner::setIsCartEnabled(bool value)
{
    m_Is_cart_enabled = value;
    m_Is_cart_enabledIsSet = true;
}

bool GetCommerce_200_response_inner::isCartEnabledIsSet() const
{
    return m_Is_cart_enabledIsSet;
}

void GetCommerce_200_response_inner::unsetIs_cart_enabled()
{
    m_Is_cart_enabledIsSet = false;
}
bool GetCommerce_200_response_inner::isIsCatalogVisible() const
{
    return m_Is_catalog_visible;
}

void GetCommerce_200_response_inner::setIsCatalogVisible(bool value)
{
    m_Is_catalog_visible = value;
    m_Is_catalog_visibleIsSet = true;
}

bool GetCommerce_200_response_inner::isCatalogVisibleIsSet() const
{
    return m_Is_catalog_visibleIsSet;
}

void GetCommerce_200_response_inner::unsetIs_catalog_visible()
{
    m_Is_catalog_visibleIsSet = false;
}


std::map<utility::string_t, web::json::value> GetCommerce_200_response_inner::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void GetCommerce_200_response_inner::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void GetCommerce_200_response_inner::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool GetCommerce_200_response_inner::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void GetCommerce_200_response_inner::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


