/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/InitiateCallResponse.h"

namespace onemsg {
namespace sdk {
namespace model {

InitiateCallResponse::InitiateCallResponse()
{
    m_Messaging_product = utility::conversions::to_string_t("");
    m_Messaging_productIsSet = false;
    m_Success = false;
    m_SuccessIsSet = false;
    m_CallsIsSet = false;
    m_Result = utility::conversions::to_string_t("");
    m_ResultIsSet = false;
    m_ResponseIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

InitiateCallResponse::~InitiateCallResponse()
{
}

void InitiateCallResponse::validate()
{
    // TODO: implement validation
}

web::json::value InitiateCallResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Messaging_productIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("messaging_product"))] = ModelBase::toJson(m_Messaging_product);
    }
    if(m_SuccessIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("success"))] = ModelBase::toJson(m_Success);
    }
    if(m_CallsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("calls"))] = ModelBase::toJson(m_Calls);
    }
    if(m_ResultIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("result"))] = ModelBase::toJson(m_Result);
    }
    if(m_ResponseIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("response"))] = ModelBase::toJson(m_Response);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool InitiateCallResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("messaging_product"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("messaging_product")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMessagingProduct;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessagingProduct);
            setMessagingProduct(refVal_setMessagingProduct);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("success")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSuccess;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSuccess);
            setSuccess(refVal_setSuccess);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("calls"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("calls")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<InitiateCallResponse_calls_inner>> refVal_setCalls;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCalls);
            setCalls(refVal_setCalls);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("result"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("result")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setResult;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResult);
            setResult(refVal_setResult);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("response"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("response")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<InitiateCallResponse_response> refVal_setResponse;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResponse);
            setResponse(refVal_setResponse);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("messaging_product"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("success"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("calls"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("result"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("response"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void InitiateCallResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Messaging_productIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("messaging_product")), m_Messaging_product));
    }
    if(m_SuccessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("success")), m_Success));
    }
    if(m_CallsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("calls")), m_Calls));
    }
    if(m_ResultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("result")), m_Result));
    }
    if(m_ResponseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("response")), m_Response));
    }
}

bool InitiateCallResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("messaging_product"))))
    {
        utility::string_t refVal_setMessagingProduct;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("messaging_product"))), refVal_setMessagingProduct );
        setMessagingProduct(refVal_setMessagingProduct);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        bool refVal_setSuccess;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("success"))), refVal_setSuccess );
        setSuccess(refVal_setSuccess);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("calls"))))
    {
        std::vector<std::shared_ptr<InitiateCallResponse_calls_inner>> refVal_setCalls;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("calls"))), refVal_setCalls );
        setCalls(refVal_setCalls);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("result"))))
    {
        utility::string_t refVal_setResult;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("result"))), refVal_setResult );
        setResult(refVal_setResult);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("response"))))
    {
        std::shared_ptr<InitiateCallResponse_response> refVal_setResponse;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("response"))), refVal_setResponse );
        setResponse(refVal_setResponse);
    }
    return ok;
}


utility::string_t InitiateCallResponse::getMessagingProduct() const
{
    return m_Messaging_product;
}


void InitiateCallResponse::setMessagingProduct(const utility::string_t& value)
{
    m_Messaging_product = value;
    m_Messaging_productIsSet = true;
}

bool InitiateCallResponse::messagingProductIsSet() const
{
    return m_Messaging_productIsSet;
}

void InitiateCallResponse::unsetMessaging_product()
{
    m_Messaging_productIsSet = false;
}
bool InitiateCallResponse::isSuccess() const
{
    return m_Success;
}

void InitiateCallResponse::setSuccess(bool value)
{
    m_Success = value;
    m_SuccessIsSet = true;
}

bool InitiateCallResponse::successIsSet() const
{
    return m_SuccessIsSet;
}

void InitiateCallResponse::unsetSuccess()
{
    m_SuccessIsSet = false;
}
std::vector<std::shared_ptr<InitiateCallResponse_calls_inner>> InitiateCallResponse::getCalls() const
{
    return m_Calls;
}


void InitiateCallResponse::setCalls(const std::vector<std::shared_ptr<InitiateCallResponse_calls_inner>>& value)
{
    m_Calls = value;
    m_CallsIsSet = true;
}

bool InitiateCallResponse::callsIsSet() const
{
    return m_CallsIsSet;
}

void InitiateCallResponse::unsetCalls()
{
    m_CallsIsSet = false;
}
utility::string_t InitiateCallResponse::getResult() const
{
    return m_Result;
}


void InitiateCallResponse::setResult(const utility::string_t& value)
{
    m_Result = value;
    m_ResultIsSet = true;
}

bool InitiateCallResponse::resultIsSet() const
{
    return m_ResultIsSet;
}

void InitiateCallResponse::unsetResult()
{
    m_ResultIsSet = false;
}
std::shared_ptr<InitiateCallResponse_response> InitiateCallResponse::getResponse() const
{
    return m_Response;
}


void InitiateCallResponse::setResponse(const std::shared_ptr<InitiateCallResponse_response>& value)
{
    m_Response = value;
    m_ResponseIsSet = true;
}

bool InitiateCallResponse::responseIsSet() const
{
    return m_ResponseIsSet;
}

void InitiateCallResponse::unsetResponse()
{
    m_ResponseIsSet = false;
}


std::map<utility::string_t, web::json::value> InitiateCallResponse::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void InitiateCallResponse::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void InitiateCallResponse::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool InitiateCallResponse::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void InitiateCallResponse::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


