/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/ListMessages_200_response.h"

namespace onemsg {
namespace chat {
namespace model {

ListMessages_200_response::ListMessages_200_response()
{
    m_Notice = utility::conversions::to_string_t("");
    m_NoticeIsSet = false;
    m_MessagesIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

ListMessages_200_response::~ListMessages_200_response()
{
}

void ListMessages_200_response::validate()
{
    // TODO: implement validation
}

web::json::value ListMessages_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_NoticeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("notice"))] = ModelBase::toJson(m_Notice);
    }
    if(m_MessagesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("messages"))] = ModelBase::toJson(m_Messages);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool ListMessages_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("notice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("notice")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNotice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotice);
            setNotice(refVal_setNotice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("messages"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("messages")));
        if(!fieldValue.is_null())
        {
            std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> refVal_setMessages;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessages);
            setMessages(refVal_setMessages);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("notice"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("messages"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void ListMessages_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_NoticeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("notice")), m_Notice));
    }
    if(m_MessagesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("messages")), m_Messages));
    }
}

bool ListMessages_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("notice"))))
    {
        utility::string_t refVal_setNotice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("notice"))), refVal_setNotice );
        setNotice(refVal_setNotice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("messages"))))
    {
        std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> refVal_setMessages;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("messages"))), refVal_setMessages );
        setMessages(refVal_setMessages);
    }
    return ok;
}


utility::string_t ListMessages_200_response::getNotice() const
{
    return m_Notice;
}


void ListMessages_200_response::setNotice(const utility::string_t& value)
{
    m_Notice = value;
    m_NoticeIsSet = true;
}

bool ListMessages_200_response::noticeIsSet() const
{
    return m_NoticeIsSet;
}

void ListMessages_200_response::unsetNotice()
{
    m_NoticeIsSet = false;
}
std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> ListMessages_200_response::getMessages() const
{
    return m_Messages;
}


void ListMessages_200_response::setMessages(const std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>>& value)
{
    m_Messages = value;
    m_MessagesIsSet = true;
}

bool ListMessages_200_response::messagesIsSet() const
{
    return m_MessagesIsSet;
}

void ListMessages_200_response::unsetMessages()
{
    m_MessagesIsSet = false;
}


std::map<utility::string_t, web::json::value> ListMessages_200_response::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void ListMessages_200_response::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void ListMessages_200_response::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool ListMessages_200_response::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void ListMessages_200_response::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


