/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/MessageSentResponse.h"

namespace onemsg {
namespace chat {
namespace model {

MessageSentResponse::MessageSentResponse()
{
    m_Sent = false;
    m_SentIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Message = utility::conversions::to_string_t("");
    m_MessageIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

MessageSentResponse::~MessageSentResponse()
{
}

void MessageSentResponse::validate()
{
    // TODO: implement validation
}

web::json::value MessageSentResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SentIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("sent"))] = ModelBase::toJson(m_Sent);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_MessageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("message"))] = ModelBase::toJson(m_Message);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool MessageSentResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sent"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sent")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSent);
            setSent(refVal_setSent);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("message")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessage);
            setMessage(refVal_setMessage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("sent"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("id"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("message"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("description"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void MessageSentResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sent")), m_Sent));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_MessageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("message")), m_Message));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
}

bool MessageSentResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sent"))))
    {
        bool refVal_setSent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sent"))), refVal_setSent );
        setSent(refVal_setSent);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        utility::string_t refVal_setMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("message"))), refVal_setMessage );
        setMessage(refVal_setMessage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    return ok;
}


bool MessageSentResponse::isSent() const
{
    return m_Sent;
}

void MessageSentResponse::setSent(bool value)
{
    m_Sent = value;
    m_SentIsSet = true;
}

bool MessageSentResponse::sentIsSet() const
{
    return m_SentIsSet;
}

void MessageSentResponse::unsetSent()
{
    m_SentIsSet = false;
}
utility::string_t MessageSentResponse::getId() const
{
    return m_Id;
}


void MessageSentResponse::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool MessageSentResponse::idIsSet() const
{
    return m_IdIsSet;
}

void MessageSentResponse::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t MessageSentResponse::getMessage() const
{
    return m_Message;
}


void MessageSentResponse::setMessage(const utility::string_t& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}

bool MessageSentResponse::messageIsSet() const
{
    return m_MessageIsSet;
}

void MessageSentResponse::unsetMessage()
{
    m_MessageIsSet = false;
}
utility::string_t MessageSentResponse::getDescription() const
{
    return m_Description;
}


void MessageSentResponse::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool MessageSentResponse::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void MessageSentResponse::unsetDescription()
{
    m_DescriptionIsSet = false;
}


std::map<utility::string_t, web::json::value> MessageSentResponse::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void MessageSentResponse::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void MessageSentResponse::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool MessageSentResponse::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void MessageSentResponse::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


