/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/ProfileInfo.h"

namespace onemsg {
namespace chat {
namespace model {

ProfileInfo::ProfileInfo()
{
    m_About = utility::conversions::to_string_t("");
    m_AboutIsSet = false;
    m_Address = utility::conversions::to_string_t("");
    m_AddressIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_Phone = utility::conversions::to_string_t("");
    m_PhoneIsSet = false;
    m_VerticalIsSet = false;
    m_Photo = utility::conversions::to_string_t("");
    m_PhotoIsSet = false;
    m_WebsitesIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

ProfileInfo::~ProfileInfo()
{
}

void ProfileInfo::validate()
{
    // TODO: implement validation
}

web::json::value ProfileInfo::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AboutIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("about"))] = ModelBase::toJson(m_About);
    }
    if(m_AddressIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("address"))] = ModelBase::toJson(m_Address);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_EmailIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_VerticalIsSet)
    {
        
        utility::string_t refVal = fromVerticalEnum(m_Vertical);
        val[utility::conversions::to_string_t(_XPLATSTR("vertical"))] = ModelBase::toJson(refVal);
        
    }
    if(m_PhotoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("photo"))] = ModelBase::toJson(m_Photo);
    }
    if(m_WebsitesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("websites"))] = ModelBase::toJson(m_Websites);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool ProfileInfo::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("about"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("about")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAbout;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAbout);
            setAbout(refVal_setAbout);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("address"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("address")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAddress;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAddress);
            setAddress(refVal_setAddress);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("vertical"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("vertical")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVertical;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVertical);
            
            setVertical(toVerticalEnum(refVal_setVertical));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("photo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("photo")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhoto;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhoto);
            setPhoto(refVal_setPhoto);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("websites"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("websites")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setWebsites;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWebsites);
            setWebsites(refVal_setWebsites);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("about"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("address"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("description"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("email"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("phone"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("vertical"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("photo"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("websites"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void ProfileInfo::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AboutIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("about")), m_About));
    }
    if(m_AddressIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("address")), m_Address));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_VerticalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("vertical")), fromVerticalEnum(m_Vertical)));
    }
    if(m_PhotoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("photo")), m_Photo));
    }
    if(m_WebsitesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("websites")), m_Websites));
    }
}

bool ProfileInfo::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("about"))))
    {
        utility::string_t refVal_setAbout;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("about"))), refVal_setAbout );
        setAbout(refVal_setAbout);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("address"))))
    {
        utility::string_t refVal_setAddress;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("address"))), refVal_setAddress );
        setAddress(refVal_setAddress);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("vertical"))))
    {
        utility::string_t refVal_setVertical;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("vertical"))), refVal_setVertical );
        setVertical(toVerticalEnum(refVal_setVertical));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("photo"))))
    {
        utility::string_t refVal_setPhoto;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("photo"))), refVal_setPhoto );
        setPhoto(refVal_setPhoto);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("websites"))))
    {
        std::vector<utility::string_t> refVal_setWebsites;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("websites"))), refVal_setWebsites );
        setWebsites(refVal_setWebsites);
    }
    return ok;
}

ProfileInfo::VerticalEnum ProfileInfo::toVerticalEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("Automotive")) {
        return VerticalEnum::AUTOMOTIVE;
    }
    
    if (value == utility::conversions::to_string_t("Beauty, Spa and Salon")) {
        return VerticalEnum::BEAUTY_SPA_AND_SALON;
    }
    
    if (value == utility::conversions::to_string_t("Clothing and Apparel")) {
        return VerticalEnum::CLOTHING_AND_APPAREL;
    }
    
    if (value == utility::conversions::to_string_t("Education")) {
        return VerticalEnum::EDUCATION;
    }
    
    if (value == utility::conversions::to_string_t("Entertainment")) {
        return VerticalEnum::ENTERTAINMENT;
    }
    
    if (value == utility::conversions::to_string_t("Event Planning and Service")) {
        return VerticalEnum::EVENT_PLANNING_AND_SERVICE;
    }
    
    if (value == utility::conversions::to_string_t("Finance and Banking")) {
        return VerticalEnum::FINANCE_AND_BANKING;
    }
    
    if (value == utility::conversions::to_string_t("Food and Grocery")) {
        return VerticalEnum::FOOD_AND_GROCERY;
    }
    
    if (value == utility::conversions::to_string_t("Public Service")) {
        return VerticalEnum::PUBLIC_SERVICE;
    }
    
    if (value == utility::conversions::to_string_t("Hotel and Lodging")) {
        return VerticalEnum::HOTEL_AND_LODGING;
    }
    
    if (value == utility::conversions::to_string_t("Medical and Health")) {
        return VerticalEnum::MEDICAL_AND_HEALTH;
    }
    
    if (value == utility::conversions::to_string_t("Non-profit")) {
        return VerticalEnum::NON_PROFIT;
    }
    
    if (value == utility::conversions::to_string_t("Professional Services")) {
        return VerticalEnum::PROFESSIONAL_SERVICES;
    }
    
    if (value == utility::conversions::to_string_t("Shopping and Retail")) {
        return VerticalEnum::SHOPPING_AND_RETAIL;
    }
    
    if (value == utility::conversions::to_string_t("Travel and Transportation")) {
        return VerticalEnum::TRAVEL_AND_TRANSPORTATION;
    }
    
    if (value == utility::conversions::to_string_t("Restaurant")) {
        return VerticalEnum::RESTAURANT;
    }
    
    if (value == utility::conversions::to_string_t("Other")) {
        return VerticalEnum::OTHER;
    }
    
    throw std::invalid_argument("Invalid value for conversion to VerticalEnum");
}


const utility::string_t ProfileInfo::fromVerticalEnum(const VerticalEnum value) const
{
    switch(value)
    {
        
        case VerticalEnum::AUTOMOTIVE: return utility::conversions::to_string_t("Automotive");
        
        case VerticalEnum::BEAUTY_SPA_AND_SALON: return utility::conversions::to_string_t("Beauty, Spa and Salon");
        
        case VerticalEnum::CLOTHING_AND_APPAREL: return utility::conversions::to_string_t("Clothing and Apparel");
        
        case VerticalEnum::EDUCATION: return utility::conversions::to_string_t("Education");
        
        case VerticalEnum::ENTERTAINMENT: return utility::conversions::to_string_t("Entertainment");
        
        case VerticalEnum::EVENT_PLANNING_AND_SERVICE: return utility::conversions::to_string_t("Event Planning and Service");
        
        case VerticalEnum::FINANCE_AND_BANKING: return utility::conversions::to_string_t("Finance and Banking");
        
        case VerticalEnum::FOOD_AND_GROCERY: return utility::conversions::to_string_t("Food and Grocery");
        
        case VerticalEnum::PUBLIC_SERVICE: return utility::conversions::to_string_t("Public Service");
        
        case VerticalEnum::HOTEL_AND_LODGING: return utility::conversions::to_string_t("Hotel and Lodging");
        
        case VerticalEnum::MEDICAL_AND_HEALTH: return utility::conversions::to_string_t("Medical and Health");
        
        case VerticalEnum::NON_PROFIT: return utility::conversions::to_string_t("Non-profit");
        
        case VerticalEnum::PROFESSIONAL_SERVICES: return utility::conversions::to_string_t("Professional Services");
        
        case VerticalEnum::SHOPPING_AND_RETAIL: return utility::conversions::to_string_t("Shopping and Retail");
        
        case VerticalEnum::TRAVEL_AND_TRANSPORTATION: return utility::conversions::to_string_t("Travel and Transportation");
        
        case VerticalEnum::RESTAURANT: return utility::conversions::to_string_t("Restaurant");
        
        case VerticalEnum::OTHER: return utility::conversions::to_string_t("Other");
        
    }
}


utility::string_t ProfileInfo::getAbout() const
{
    return m_About;
}


void ProfileInfo::setAbout(const utility::string_t& value)
{
    m_About = value;
    m_AboutIsSet = true;
}

bool ProfileInfo::aboutIsSet() const
{
    return m_AboutIsSet;
}

void ProfileInfo::unsetAbout()
{
    m_AboutIsSet = false;
}
utility::string_t ProfileInfo::getAddress() const
{
    return m_Address;
}


void ProfileInfo::setAddress(const utility::string_t& value)
{
    m_Address = value;
    m_AddressIsSet = true;
}

bool ProfileInfo::addressIsSet() const
{
    return m_AddressIsSet;
}

void ProfileInfo::unsetAddress()
{
    m_AddressIsSet = false;
}
utility::string_t ProfileInfo::getDescription() const
{
    return m_Description;
}


void ProfileInfo::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool ProfileInfo::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void ProfileInfo::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t ProfileInfo::getEmail() const
{
    return m_Email;
}


void ProfileInfo::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool ProfileInfo::emailIsSet() const
{
    return m_EmailIsSet;
}

void ProfileInfo::unsetEmail()
{
    m_EmailIsSet = false;
}
utility::string_t ProfileInfo::getPhone() const
{
    return m_Phone;
}


void ProfileInfo::setPhone(const utility::string_t& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool ProfileInfo::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void ProfileInfo::unsetPhone()
{
    m_PhoneIsSet = false;
}
ProfileInfo::VerticalEnum ProfileInfo::getVertical() const
{
    return m_Vertical;
}


void ProfileInfo::setVertical(const VerticalEnum value)
{
    m_Vertical = value;
    m_VerticalIsSet = true;
}

bool ProfileInfo::verticalIsSet() const
{
    return m_VerticalIsSet;
}

void ProfileInfo::unsetVertical()
{
    m_VerticalIsSet = false;
}
utility::string_t ProfileInfo::getPhoto() const
{
    return m_Photo;
}


void ProfileInfo::setPhoto(const utility::string_t& value)
{
    m_Photo = value;
    m_PhotoIsSet = true;
}

bool ProfileInfo::photoIsSet() const
{
    return m_PhotoIsSet;
}

void ProfileInfo::unsetPhoto()
{
    m_PhotoIsSet = false;
}
std::vector<utility::string_t> ProfileInfo::getWebsites() const
{
    return m_Websites;
}


void ProfileInfo::setWebsites(const std::vector<utility::string_t>& value)
{
    m_Websites = value;
    m_WebsitesIsSet = true;
}

bool ProfileInfo::websitesIsSet() const
{
    return m_WebsitesIsSet;
}

void ProfileInfo::unsetWebsites()
{
    m_WebsitesIsSet = false;
}


std::map<utility::string_t, web::json::value> ProfileInfo::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void ProfileInfo::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void ProfileInfo::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool ProfileInfo::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void ProfileInfo::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


