/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/SendList_request.h"

namespace onemsg {
namespace chat {
namespace model {

SendList_request::SendList_request()
{
    m_Phone = utility::conversions::to_string_t("");
    m_PhoneIsSet = false;
    m_Body = utility::conversions::to_string_t("");
    m_BodyIsSet = false;
    m_ButtonText = utility::conversions::to_string_t("");
    m_ButtonTextIsSet = false;
    m_Action = utility::conversions::to_string_t("");
    m_ActionIsSet = false;
    m_SectionsIsSet = false;
}

SendList_request::~SendList_request()
{
}

void SendList_request::validate()
{
    // TODO: implement validation
}

web::json::value SendList_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_BodyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("body"))] = ModelBase::toJson(m_Body);
    }
    if(m_ButtonTextIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("buttonText"))] = ModelBase::toJson(m_ButtonText);
    }
    if(m_ActionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("action"))] = ModelBase::toJson(m_Action);
    }
    if(m_SectionsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("sections"))] = ModelBase::toJson(m_Sections);
    }

    return val;
}

bool SendList_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("body")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBody;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBody);
            setBody(refVal_setBody);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("buttonText"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("buttonText")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setButtonText;
            ok &= ModelBase::fromJson(fieldValue, refVal_setButtonText);
            setButtonText(refVal_setButtonText);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("action"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("action")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAction;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAction);
            setAction(refVal_setAction);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sections"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sections")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SendList_request_sections_inner>> refVal_setSections;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSections);
            setSections(refVal_setSections);
            
        }
    }
    return ok;
}

void SendList_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_BodyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("body")), m_Body));
    }
    if(m_ButtonTextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("buttonText")), m_ButtonText));
    }
    if(m_ActionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("action")), m_Action));
    }
    if(m_SectionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sections")), m_Sections));
    }
}

bool SendList_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        utility::string_t refVal_setBody;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("body"))), refVal_setBody );
        setBody(refVal_setBody);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("buttonText"))))
    {
        utility::string_t refVal_setButtonText;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("buttonText"))), refVal_setButtonText );
        setButtonText(refVal_setButtonText);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("action"))))
    {
        utility::string_t refVal_setAction;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("action"))), refVal_setAction );
        setAction(refVal_setAction);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sections"))))
    {
        std::vector<std::shared_ptr<SendList_request_sections_inner>> refVal_setSections;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sections"))), refVal_setSections );
        setSections(refVal_setSections);
    }
    return ok;
}


utility::string_t SendList_request::getPhone() const
{
    return m_Phone;
}


void SendList_request::setPhone(const utility::string_t& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SendList_request::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SendList_request::unsetPhone()
{
    m_PhoneIsSet = false;
}
utility::string_t SendList_request::getBody() const
{
    return m_Body;
}


void SendList_request::setBody(const utility::string_t& value)
{
    m_Body = value;
    m_BodyIsSet = true;
}

bool SendList_request::bodyIsSet() const
{
    return m_BodyIsSet;
}

void SendList_request::unsetBody()
{
    m_BodyIsSet = false;
}
utility::string_t SendList_request::getButtonText() const
{
    return m_ButtonText;
}


void SendList_request::setButtonText(const utility::string_t& value)
{
    m_ButtonText = value;
    m_ButtonTextIsSet = true;
}

bool SendList_request::buttonTextIsSet() const
{
    return m_ButtonTextIsSet;
}

void SendList_request::unsetButtonText()
{
    m_ButtonTextIsSet = false;
}
utility::string_t SendList_request::getAction() const
{
    return m_Action;
}


void SendList_request::setAction(const utility::string_t& value)
{
    m_Action = value;
    m_ActionIsSet = true;
}

bool SendList_request::actionIsSet() const
{
    return m_ActionIsSet;
}

void SendList_request::unsetAction()
{
    m_ActionIsSet = false;
}
std::vector<std::shared_ptr<SendList_request_sections_inner>> SendList_request::getSections() const
{
    return m_Sections;
}


void SendList_request::setSections(const std::vector<std::shared_ptr<SendList_request_sections_inner>>& value)
{
    m_Sections = value;
    m_SectionsIsSet = true;
}

bool SendList_request::sectionsIsSet() const
{
    return m_SectionsIsSet;
}

void SendList_request::unsetSections()
{
    m_SectionsIsSet = false;
}

}
}
}


