/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/SendPaymentRequest_request.h"

namespace onemsg {
namespace chat {
namespace model {

SendPaymentRequest_request::SendPaymentRequest_request()
{
    m_Phone = 0;
    m_PhoneIsSet = false;
    m_RegionIsSet = false;
    m_Body = utility::conversions::to_string_t("");
    m_BodyIsSet = false;
    m_InteractiveIsSet = false;
    m_ActionIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

SendPaymentRequest_request::~SendPaymentRequest_request()
{
}

void SendPaymentRequest_request::validate()
{
    // TODO: implement validation
}

web::json::value SendPaymentRequest_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_RegionIsSet)
    {
        
        utility::string_t refVal = fromRegionEnum(m_Region);
        val[utility::conversions::to_string_t(_XPLATSTR("region"))] = ModelBase::toJson(refVal);
        
    }
    if(m_BodyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("body"))] = ModelBase::toJson(m_Body);
    }
    if(m_InteractiveIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("interactive"))] = ModelBase::toJson(m_Interactive);
    }
    if(m_ActionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("action"))] = ModelBase::toJson(m_Action);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool SendPaymentRequest_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("region"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("region")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRegion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRegion);
            
            setRegion(toRegionEnum(refVal_setRegion));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("body")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBody;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBody);
            setBody(refVal_setBody);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("interactive"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("interactive")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setInteractive;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInteractive);
            setInteractive(refVal_setInteractive);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("action"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("action")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setAction;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAction);
            setAction(refVal_setAction);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("phone"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("region"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("body"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("interactive"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("action"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void SendPaymentRequest_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_RegionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("region")), fromRegionEnum(m_Region)));
    }
    if(m_BodyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("body")), m_Body));
    }
    if(m_InteractiveIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("interactive")), m_Interactive));
    }
    if(m_ActionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("action")), m_Action));
    }
}

bool SendPaymentRequest_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        int32_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("region"))))
    {
        utility::string_t refVal_setRegion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("region"))), refVal_setRegion );
        setRegion(toRegionEnum(refVal_setRegion));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        utility::string_t refVal_setBody;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("body"))), refVal_setBody );
        setBody(refVal_setBody);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("interactive"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setInteractive;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("interactive"))), refVal_setInteractive );
        setInteractive(refVal_setInteractive);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("action"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setAction;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("action"))), refVal_setAction );
        setAction(refVal_setAction);
    }
    return ok;
}

SendPaymentRequest_request::RegionEnum SendPaymentRequest_request::toRegionEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("IN")) {
        return RegionEnum::IN;
    }
    
    if (value == utility::conversions::to_string_t("SG")) {
        return RegionEnum::SG;
    }
    
    if (value == utility::conversions::to_string_t("BR")) {
        return RegionEnum::BR;
    }
    
    throw std::invalid_argument("Invalid value for conversion to RegionEnum");
}


const utility::string_t SendPaymentRequest_request::fromRegionEnum(const RegionEnum value) const
{
    switch(value)
    {
        
        case RegionEnum::IN: return utility::conversions::to_string_t("IN");
        
        case RegionEnum::SG: return utility::conversions::to_string_t("SG");
        
        case RegionEnum::BR: return utility::conversions::to_string_t("BR");
        
    }
}


int32_t SendPaymentRequest_request::getPhone() const
{
    return m_Phone;
}

void SendPaymentRequest_request::setPhone(int32_t value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SendPaymentRequest_request::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SendPaymentRequest_request::unsetPhone()
{
    m_PhoneIsSet = false;
}
SendPaymentRequest_request::RegionEnum SendPaymentRequest_request::getRegion() const
{
    return m_Region;
}


void SendPaymentRequest_request::setRegion(const RegionEnum value)
{
    m_Region = value;
    m_RegionIsSet = true;
}

bool SendPaymentRequest_request::regionIsSet() const
{
    return m_RegionIsSet;
}

void SendPaymentRequest_request::unsetRegion()
{
    m_RegionIsSet = false;
}
utility::string_t SendPaymentRequest_request::getBody() const
{
    return m_Body;
}


void SendPaymentRequest_request::setBody(const utility::string_t& value)
{
    m_Body = value;
    m_BodyIsSet = true;
}

bool SendPaymentRequest_request::bodyIsSet() const
{
    return m_BodyIsSet;
}

void SendPaymentRequest_request::unsetBody()
{
    m_BodyIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> SendPaymentRequest_request::getInteractive() const
{
    return m_Interactive;
}


void SendPaymentRequest_request::setInteractive(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Interactive = value;
    m_InteractiveIsSet = true;
}

bool SendPaymentRequest_request::interactiveIsSet() const
{
    return m_InteractiveIsSet;
}

void SendPaymentRequest_request::unsetInteractive()
{
    m_InteractiveIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> SendPaymentRequest_request::getAction() const
{
    return m_Action;
}


void SendPaymentRequest_request::setAction(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Action = value;
    m_ActionIsSet = true;
}

bool SendPaymentRequest_request::actionIsSet() const
{
    return m_ActionIsSet;
}

void SendPaymentRequest_request::unsetAction()
{
    m_ActionIsSet = false;
}


std::map<utility::string_t, web::json::value> SendPaymentRequest_request::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void SendPaymentRequest_request::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void SendPaymentRequest_request::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool SendPaymentRequest_request::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void SendPaymentRequest_request::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


