/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/SendTemplate_request.h"

namespace onemsg {
namespace chat {
namespace model {

SendTemplate_request::SendTemplate_request()
{
    m_r_template = utility::conversions::to_string_t("");
    m_r_templateIsSet = false;
    m_LanguageIsSet = false;
    m_r_namespace = utility::conversions::to_string_t("");
    m_r_namespaceIsSet = false;
    m_ParamsIsSet = false;
    m_Phone = utility::conversions::to_string_t("");
    m_PhoneIsSet = false;
    m_UseMMlite = false;
    m_UseMMliteIsSet = false;
    m_MessageActivitySharing = false;
    m_MessageActivitySharingIsSet = false;
    m_MessageSendTtlSeconds = 0;
    m_MessageSendTtlSecondsIsSet = false;
}

SendTemplate_request::~SendTemplate_request()
{
}

void SendTemplate_request::validate()
{
    // TODO: implement validation
}

web::json::value SendTemplate_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_r_templateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("template"))] = ModelBase::toJson(m_r_template);
    }
    if(m_LanguageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("language"))] = ModelBase::toJson(m_Language);
    }
    if(m_r_namespaceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("namespace"))] = ModelBase::toJson(m_r_namespace);
    }
    if(m_ParamsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("params"))] = ModelBase::toJson(m_Params);
    }
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_UseMMliteIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("useMMlite"))] = ModelBase::toJson(m_UseMMlite);
    }
    if(m_MessageActivitySharingIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("messageActivitySharing"))] = ModelBase::toJson(m_MessageActivitySharing);
    }
    if(m_MessageSendTtlSecondsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("messageSendTtlSeconds"))] = ModelBase::toJson(m_MessageSendTtlSeconds);
    }

    return val;
}

bool SendTemplate_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("template"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("template")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRTemplate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRTemplate);
            setRTemplate(refVal_setRTemplate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("language"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("language")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SendTemplate_request_language> refVal_setLanguage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLanguage);
            setLanguage(refVal_setLanguage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("namespace"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("namespace")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRNamespace;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRNamespace);
            setRNamespace(refVal_setRNamespace);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("params"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("params")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AnyType>> refVal_setParams;
            ok &= ModelBase::fromJson(fieldValue, refVal_setParams);
            setParams(refVal_setParams);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("useMMlite"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("useMMlite")));
        if(!fieldValue.is_null())
        {
            bool refVal_setUseMMlite;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUseMMlite);
            setUseMMlite(refVal_setUseMMlite);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("messageActivitySharing"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("messageActivitySharing")));
        if(!fieldValue.is_null())
        {
            bool refVal_setMessageActivitySharing;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessageActivitySharing);
            setMessageActivitySharing(refVal_setMessageActivitySharing);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("messageSendTtlSeconds"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("messageSendTtlSeconds")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMessageSendTtlSeconds;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessageSendTtlSeconds);
            setMessageSendTtlSeconds(refVal_setMessageSendTtlSeconds);
            
        }
    }
    return ok;
}

void SendTemplate_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_r_templateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("template")), m_r_template));
    }
    if(m_LanguageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("language")), m_Language));
    }
    if(m_r_namespaceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("namespace")), m_r_namespace));
    }
    if(m_ParamsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("params")), m_Params));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_UseMMliteIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("useMMlite")), m_UseMMlite));
    }
    if(m_MessageActivitySharingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("messageActivitySharing")), m_MessageActivitySharing));
    }
    if(m_MessageSendTtlSecondsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("messageSendTtlSeconds")), m_MessageSendTtlSeconds));
    }
}

bool SendTemplate_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("template"))))
    {
        utility::string_t refVal_setRTemplate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("template"))), refVal_setRTemplate );
        setRTemplate(refVal_setRTemplate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("language"))))
    {
        std::shared_ptr<SendTemplate_request_language> refVal_setLanguage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("language"))), refVal_setLanguage );
        setLanguage(refVal_setLanguage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("namespace"))))
    {
        utility::string_t refVal_setRNamespace;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("namespace"))), refVal_setRNamespace );
        setRNamespace(refVal_setRNamespace);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("params"))))
    {
        std::vector<std::shared_ptr<AnyType>> refVal_setParams;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("params"))), refVal_setParams );
        setParams(refVal_setParams);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("useMMlite"))))
    {
        bool refVal_setUseMMlite;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("useMMlite"))), refVal_setUseMMlite );
        setUseMMlite(refVal_setUseMMlite);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("messageActivitySharing"))))
    {
        bool refVal_setMessageActivitySharing;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("messageActivitySharing"))), refVal_setMessageActivitySharing );
        setMessageActivitySharing(refVal_setMessageActivitySharing);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("messageSendTtlSeconds"))))
    {
        int32_t refVal_setMessageSendTtlSeconds;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("messageSendTtlSeconds"))), refVal_setMessageSendTtlSeconds );
        setMessageSendTtlSeconds(refVal_setMessageSendTtlSeconds);
    }
    return ok;
}


utility::string_t SendTemplate_request::getRTemplate() const
{
    return m_r_template;
}


void SendTemplate_request::setRTemplate(const utility::string_t& value)
{
    m_r_template = value;
    m_r_templateIsSet = true;
}

bool SendTemplate_request::rTemplateIsSet() const
{
    return m_r_templateIsSet;
}

void SendTemplate_request::unsetr_template()
{
    m_r_templateIsSet = false;
}
std::shared_ptr<SendTemplate_request_language> SendTemplate_request::getLanguage() const
{
    return m_Language;
}


void SendTemplate_request::setLanguage(const std::shared_ptr<SendTemplate_request_language>& value)
{
    m_Language = value;
    m_LanguageIsSet = true;
}

bool SendTemplate_request::languageIsSet() const
{
    return m_LanguageIsSet;
}

void SendTemplate_request::unsetLanguage()
{
    m_LanguageIsSet = false;
}
utility::string_t SendTemplate_request::getRNamespace() const
{
    return m_r_namespace;
}


void SendTemplate_request::setRNamespace(const utility::string_t& value)
{
    m_r_namespace = value;
    m_r_namespaceIsSet = true;
}

bool SendTemplate_request::rNamespaceIsSet() const
{
    return m_r_namespaceIsSet;
}

void SendTemplate_request::unsetr_namespace()
{
    m_r_namespaceIsSet = false;
}
std::vector<std::shared_ptr<AnyType>> SendTemplate_request::getParams() const
{
    return m_Params;
}


void SendTemplate_request::setParams(const std::vector<std::shared_ptr<AnyType>>& value)
{
    m_Params = value;
    m_ParamsIsSet = true;
}

bool SendTemplate_request::paramsIsSet() const
{
    return m_ParamsIsSet;
}

void SendTemplate_request::unsetParams()
{
    m_ParamsIsSet = false;
}
utility::string_t SendTemplate_request::getPhone() const
{
    return m_Phone;
}


void SendTemplate_request::setPhone(const utility::string_t& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SendTemplate_request::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SendTemplate_request::unsetPhone()
{
    m_PhoneIsSet = false;
}
bool SendTemplate_request::isUseMMlite() const
{
    return m_UseMMlite;
}

void SendTemplate_request::setUseMMlite(bool value)
{
    m_UseMMlite = value;
    m_UseMMliteIsSet = true;
}

bool SendTemplate_request::useMMliteIsSet() const
{
    return m_UseMMliteIsSet;
}

void SendTemplate_request::unsetUseMMlite()
{
    m_UseMMliteIsSet = false;
}
bool SendTemplate_request::isMessageActivitySharing() const
{
    return m_MessageActivitySharing;
}

void SendTemplate_request::setMessageActivitySharing(bool value)
{
    m_MessageActivitySharing = value;
    m_MessageActivitySharingIsSet = true;
}

bool SendTemplate_request::messageActivitySharingIsSet() const
{
    return m_MessageActivitySharingIsSet;
}

void SendTemplate_request::unsetMessageActivitySharing()
{
    m_MessageActivitySharingIsSet = false;
}
int32_t SendTemplate_request::getMessageSendTtlSeconds() const
{
    return m_MessageSendTtlSeconds;
}

void SendTemplate_request::setMessageSendTtlSeconds(int32_t value)
{
    m_MessageSendTtlSeconds = value;
    m_MessageSendTtlSecondsIsSet = true;
}

bool SendTemplate_request::messageSendTtlSecondsIsSet() const
{
    return m_MessageSendTtlSecondsIsSet;
}

void SendTemplate_request::unsetMessageSendTtlSeconds()
{
    m_MessageSendTtlSecondsIsSet = false;
}

}
}
}


