/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendLocationRequest_request.h"

namespace onemsg {
namespace sdk {
namespace model {

SendLocationRequest_request::SendLocationRequest_request()
{
    m_Phone = utility::conversions::to_string_t("");
    m_PhoneIsSet = false;
    m_Body = utility::conversions::to_string_t("");
    m_BodyIsSet = false;
}

SendLocationRequest_request::~SendLocationRequest_request()
{
}

void SendLocationRequest_request::validate()
{
    // TODO: implement validation
}

web::json::value SendLocationRequest_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_BodyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("body"))] = ModelBase::toJson(m_Body);
    }

    return val;
}

bool SendLocationRequest_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("body")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBody;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBody);
            setBody(refVal_setBody);
            
        }
    }
    return ok;
}

void SendLocationRequest_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_BodyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("body")), m_Body));
    }
}

bool SendLocationRequest_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        utility::string_t refVal_setBody;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("body"))), refVal_setBody );
        setBody(refVal_setBody);
    }
    return ok;
}


utility::string_t SendLocationRequest_request::getPhone() const
{
    return m_Phone;
}


void SendLocationRequest_request::setPhone(const utility::string_t& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SendLocationRequest_request::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SendLocationRequest_request::unsetPhone()
{
    m_PhoneIsSet = false;
}
utility::string_t SendLocationRequest_request::getBody() const
{
    return m_Body;
}


void SendLocationRequest_request::setBody(const utility::string_t& value)
{
    m_Body = value;
    m_BodyIsSet = true;
}

bool SendLocationRequest_request::bodyIsSet() const
{
    return m_BodyIsSet;
}

void SendLocationRequest_request::unsetBody()
{
    m_BodyIsSet = false;
}

}
}
}


