/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/SendContact_request_contacts_inner_phones_inner.h"

namespace onemsg {
namespace chat {
namespace model {

SendContact_request_contacts_inner_phones_inner::SendContact_request_contacts_inner_phones_inner()
{
    m_Phone = utility::conversions::to_string_t("");
    m_PhoneIsSet = false;
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
    m_Wa_id = utility::conversions::to_string_t("");
    m_Wa_idIsSet = false;
}

SendContact_request_contacts_inner_phones_inner::~SendContact_request_contacts_inner_phones_inner()
{
}

void SendContact_request_contacts_inner_phones_inner::validate()
{
    // TODO: implement validation
}

web::json::value SendContact_request_contacts_inner_phones_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_TypeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type);
    }
    if(m_Wa_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("wa_id"))] = ModelBase::toJson(m_Wa_id);
    }

    return val;
}

bool SendContact_request_contacts_inner_phones_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("wa_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("wa_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWaId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWaId);
            setWaId(refVal_setWaId);
            
        }
    }
    return ok;
}

void SendContact_request_contacts_inner_phones_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type));
    }
    if(m_Wa_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("wa_id")), m_Wa_id));
    }
}

bool SendContact_request_contacts_inner_phones_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("wa_id"))))
    {
        utility::string_t refVal_setWaId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("wa_id"))), refVal_setWaId );
        setWaId(refVal_setWaId);
    }
    return ok;
}


utility::string_t SendContact_request_contacts_inner_phones_inner::getPhone() const
{
    return m_Phone;
}


void SendContact_request_contacts_inner_phones_inner::setPhone(const utility::string_t& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SendContact_request_contacts_inner_phones_inner::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SendContact_request_contacts_inner_phones_inner::unsetPhone()
{
    m_PhoneIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_phones_inner::getType() const
{
    return m_Type;
}


void SendContact_request_contacts_inner_phones_inner::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool SendContact_request_contacts_inner_phones_inner::typeIsSet() const
{
    return m_TypeIsSet;
}

void SendContact_request_contacts_inner_phones_inner::unsetType()
{
    m_TypeIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_phones_inner::getWaId() const
{
    return m_Wa_id;
}


void SendContact_request_contacts_inner_phones_inner::setWaId(const utility::string_t& value)
{
    m_Wa_id = value;
    m_Wa_idIsSet = true;
}

bool SendContact_request_contacts_inner_phones_inner::waIdIsSet() const
{
    return m_Wa_idIsSet;
}

void SendContact_request_contacts_inner_phones_inner::unsetWa_id()
{
    m_Wa_idIsSet = false;
}

}
}
}


