/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/SendContact_request_contacts_inner_org.h"

namespace onemsg {
namespace chat {
namespace model {

SendContact_request_contacts_inner_org::SendContact_request_contacts_inner_org()
{
    m_Company = utility::conversions::to_string_t("");
    m_CompanyIsSet = false;
    m_Department = utility::conversions::to_string_t("");
    m_DepartmentIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
}

SendContact_request_contacts_inner_org::~SendContact_request_contacts_inner_org()
{
}

void SendContact_request_contacts_inner_org::validate()
{
    // TODO: implement validation
}

web::json::value SendContact_request_contacts_inner_org::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CompanyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("company"))] = ModelBase::toJson(m_Company);
    }
    if(m_DepartmentIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("department"))] = ModelBase::toJson(m_Department);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }

    return val;
}

bool SendContact_request_contacts_inner_org::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("company"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("company")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCompany;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCompany);
            setCompany(refVal_setCompany);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("department"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("department")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDepartment;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDepartment);
            setDepartment(refVal_setDepartment);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    return ok;
}

void SendContact_request_contacts_inner_org::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CompanyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("company")), m_Company));
    }
    if(m_DepartmentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("department")), m_Department));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
}

bool SendContact_request_contacts_inner_org::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("company"))))
    {
        utility::string_t refVal_setCompany;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("company"))), refVal_setCompany );
        setCompany(refVal_setCompany);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("department"))))
    {
        utility::string_t refVal_setDepartment;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("department"))), refVal_setDepartment );
        setDepartment(refVal_setDepartment);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    return ok;
}


utility::string_t SendContact_request_contacts_inner_org::getCompany() const
{
    return m_Company;
}


void SendContact_request_contacts_inner_org::setCompany(const utility::string_t& value)
{
    m_Company = value;
    m_CompanyIsSet = true;
}

bool SendContact_request_contacts_inner_org::companyIsSet() const
{
    return m_CompanyIsSet;
}

void SendContact_request_contacts_inner_org::unsetCompany()
{
    m_CompanyIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_org::getDepartment() const
{
    return m_Department;
}


void SendContact_request_contacts_inner_org::setDepartment(const utility::string_t& value)
{
    m_Department = value;
    m_DepartmentIsSet = true;
}

bool SendContact_request_contacts_inner_org::departmentIsSet() const
{
    return m_DepartmentIsSet;
}

void SendContact_request_contacts_inner_org::unsetDepartment()
{
    m_DepartmentIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_org::getTitle() const
{
    return m_Title;
}


void SendContact_request_contacts_inner_org::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool SendContact_request_contacts_inner_org::titleIsSet() const
{
    return m_TitleIsSet;
}

void SendContact_request_contacts_inner_org::unsetTitle()
{
    m_TitleIsSet = false;
}

}
}
}


