/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendContact_request_contacts_inner.h"

namespace onemsg {
namespace chat {
namespace model {

SendContact_request_contacts_inner::SendContact_request_contacts_inner()
{
    m_NameIsSet = false;
    m_Birthday = utility::conversions::to_string_t("");
    m_BirthdayIsSet = false;
    m_AddressesIsSet = false;
    m_EmailsIsSet = false;
    m_OrgIsSet = false;
    m_PhonesIsSet = false;
    m_UrlsIsSet = false;
}

SendContact_request_contacts_inner::~SendContact_request_contacts_inner()
{
}

void SendContact_request_contacts_inner::validate()
{
    // TODO: implement validation
}

web::json::value SendContact_request_contacts_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_BirthdayIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("birthday"))] = ModelBase::toJson(m_Birthday);
    }
    if(m_AddressesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("addresses"))] = ModelBase::toJson(m_Addresses);
    }
    if(m_EmailsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("emails"))] = ModelBase::toJson(m_Emails);
    }
    if(m_OrgIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("org"))] = ModelBase::toJson(m_Org);
    }
    if(m_PhonesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phones"))] = ModelBase::toJson(m_Phones);
    }
    if(m_UrlsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("urls"))] = ModelBase::toJson(m_Urls);
    }

    return val;
}

bool SendContact_request_contacts_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SendContact_request_contacts_inner_name> refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("birthday"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("birthday")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBirthday;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBirthday);
            setBirthday(refVal_setBirthday);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("addresses"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("addresses")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AnyType>> refVal_setAddresses;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAddresses);
            setAddresses(refVal_setAddresses);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("emails"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("emails")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AnyType>> refVal_setEmails;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmails);
            setEmails(refVal_setEmails);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("org"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("org")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SendContact_request_contacts_inner_org> refVal_setOrg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrg);
            setOrg(refVal_setOrg);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phones"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phones")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SendContact_request_contacts_inner_phones_inner>> refVal_setPhones;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhones);
            setPhones(refVal_setPhones);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("urls"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("urls")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<AnyType>> refVal_setUrls;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrls);
            setUrls(refVal_setUrls);
            
        }
    }
    return ok;
}

void SendContact_request_contacts_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_BirthdayIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("birthday")), m_Birthday));
    }
    if(m_AddressesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("addresses")), m_Addresses));
    }
    if(m_EmailsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("emails")), m_Emails));
    }
    if(m_OrgIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("org")), m_Org));
    }
    if(m_PhonesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phones")), m_Phones));
    }
    if(m_UrlsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("urls")), m_Urls));
    }
}

bool SendContact_request_contacts_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        std::shared_ptr<SendContact_request_contacts_inner_name> refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("birthday"))))
    {
        utility::string_t refVal_setBirthday;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("birthday"))), refVal_setBirthday );
        setBirthday(refVal_setBirthday);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("addresses"))))
    {
        std::vector<std::shared_ptr<AnyType>> refVal_setAddresses;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("addresses"))), refVal_setAddresses );
        setAddresses(refVal_setAddresses);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("emails"))))
    {
        std::vector<std::shared_ptr<AnyType>> refVal_setEmails;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("emails"))), refVal_setEmails );
        setEmails(refVal_setEmails);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("org"))))
    {
        std::shared_ptr<SendContact_request_contacts_inner_org> refVal_setOrg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("org"))), refVal_setOrg );
        setOrg(refVal_setOrg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phones"))))
    {
        std::vector<std::shared_ptr<SendContact_request_contacts_inner_phones_inner>> refVal_setPhones;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phones"))), refVal_setPhones );
        setPhones(refVal_setPhones);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("urls"))))
    {
        std::vector<std::shared_ptr<AnyType>> refVal_setUrls;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("urls"))), refVal_setUrls );
        setUrls(refVal_setUrls);
    }
    return ok;
}


std::shared_ptr<SendContact_request_contacts_inner_name> SendContact_request_contacts_inner::getName() const
{
    return m_Name;
}


void SendContact_request_contacts_inner::setName(const std::shared_ptr<SendContact_request_contacts_inner_name>& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool SendContact_request_contacts_inner::nameIsSet() const
{
    return m_NameIsSet;
}

void SendContact_request_contacts_inner::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t SendContact_request_contacts_inner::getBirthday() const
{
    return m_Birthday;
}


void SendContact_request_contacts_inner::setBirthday(const utility::string_t& value)
{
    m_Birthday = value;
    m_BirthdayIsSet = true;
}

bool SendContact_request_contacts_inner::birthdayIsSet() const
{
    return m_BirthdayIsSet;
}

void SendContact_request_contacts_inner::unsetBirthday()
{
    m_BirthdayIsSet = false;
}
std::vector<std::shared_ptr<AnyType>> SendContact_request_contacts_inner::getAddresses() const
{
    return m_Addresses;
}


void SendContact_request_contacts_inner::setAddresses(const std::vector<std::shared_ptr<AnyType>>& value)
{
    m_Addresses = value;
    m_AddressesIsSet = true;
}

bool SendContact_request_contacts_inner::addressesIsSet() const
{
    return m_AddressesIsSet;
}

void SendContact_request_contacts_inner::unsetAddresses()
{
    m_AddressesIsSet = false;
}
std::vector<std::shared_ptr<AnyType>> SendContact_request_contacts_inner::getEmails() const
{
    return m_Emails;
}


void SendContact_request_contacts_inner::setEmails(const std::vector<std::shared_ptr<AnyType>>& value)
{
    m_Emails = value;
    m_EmailsIsSet = true;
}

bool SendContact_request_contacts_inner::emailsIsSet() const
{
    return m_EmailsIsSet;
}

void SendContact_request_contacts_inner::unsetEmails()
{
    m_EmailsIsSet = false;
}
std::shared_ptr<SendContact_request_contacts_inner_org> SendContact_request_contacts_inner::getOrg() const
{
    return m_Org;
}


void SendContact_request_contacts_inner::setOrg(const std::shared_ptr<SendContact_request_contacts_inner_org>& value)
{
    m_Org = value;
    m_OrgIsSet = true;
}

bool SendContact_request_contacts_inner::orgIsSet() const
{
    return m_OrgIsSet;
}

void SendContact_request_contacts_inner::unsetOrg()
{
    m_OrgIsSet = false;
}
std::vector<std::shared_ptr<SendContact_request_contacts_inner_phones_inner>> SendContact_request_contacts_inner::getPhones() const
{
    return m_Phones;
}


void SendContact_request_contacts_inner::setPhones(const std::vector<std::shared_ptr<SendContact_request_contacts_inner_phones_inner>>& value)
{
    m_Phones = value;
    m_PhonesIsSet = true;
}

bool SendContact_request_contacts_inner::phonesIsSet() const
{
    return m_PhonesIsSet;
}

void SendContact_request_contacts_inner::unsetPhones()
{
    m_PhonesIsSet = false;
}
std::vector<std::shared_ptr<AnyType>> SendContact_request_contacts_inner::getUrls() const
{
    return m_Urls;
}


void SendContact_request_contacts_inner::setUrls(const std::vector<std::shared_ptr<AnyType>>& value)
{
    m_Urls = value;
    m_UrlsIsSet = true;
}

bool SendContact_request_contacts_inner::urlsIsSet() const
{
    return m_UrlsIsSet;
}

void SendContact_request_contacts_inner::unsetUrls()
{
    m_UrlsIsSet = false;
}

}
}
}


