/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendFileRequest.h"

namespace onemsg {
namespace chat {
namespace model {

SendFileRequest::SendFileRequest()
{
    m_Body = utility::conversions::to_string_t("");
    m_BodyIsSet = false;
    m_Filename = utility::conversions::to_string_t("");
    m_FilenameIsSet = false;
    m_MediaId = utility::conversions::to_string_t("");
    m_MediaIdIsSet = false;
    m_MediaTypeIsSet = false;
    m_Voice = false;
    m_VoiceIsSet = false;
    m_Caption = utility::conversions::to_string_t("");
    m_CaptionIsSet = false;
    m_QuotedMsgId = utility::conversions::to_string_t("");
    m_QuotedMsgIdIsSet = false;
    m_ChatId = utility::conversions::to_string_t("");
    m_ChatIdIsSet = false;
    m_Phone = 0;
    m_PhoneIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

SendFileRequest::~SendFileRequest()
{
}

void SendFileRequest::validate()
{
    // TODO: implement validation
}

web::json::value SendFileRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_BodyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("body"))] = ModelBase::toJson(m_Body);
    }
    if(m_FilenameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("filename"))] = ModelBase::toJson(m_Filename);
    }
    if(m_MediaIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("mediaId"))] = ModelBase::toJson(m_MediaId);
    }
    if(m_MediaTypeIsSet)
    {
        
        utility::string_t refVal = fromMediaTypeEnum(m_MediaType);
        val[utility::conversions::to_string_t(_XPLATSTR("mediaType"))] = ModelBase::toJson(refVal);
        
    }
    if(m_VoiceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("voice"))] = ModelBase::toJson(m_Voice);
    }
    if(m_CaptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("caption"))] = ModelBase::toJson(m_Caption);
    }
    if(m_QuotedMsgIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))] = ModelBase::toJson(m_QuotedMsgId);
    }
    if(m_ChatIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("chatId"))] = ModelBase::toJson(m_ChatId);
    }
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool SendFileRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("body")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBody;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBody);
            setBody(refVal_setBody);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("filename"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("filename")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFilename;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFilename);
            setFilename(refVal_setFilename);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mediaId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mediaId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMediaId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMediaId);
            setMediaId(refVal_setMediaId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mediaType"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mediaType")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMediaType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMediaType);
            
            setMediaType(toMediaTypeEnum(refVal_setMediaType));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("voice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("voice")));
        if(!fieldValue.is_null())
        {
            bool refVal_setVoice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVoice);
            setVoice(refVal_setVoice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("caption"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("caption")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCaption;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCaption);
            setCaption(refVal_setCaption);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuotedMsgId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuotedMsgId);
            setQuotedMsgId(refVal_setQuotedMsgId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("chatId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("chatId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setChatId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChatId);
            setChatId(refVal_setChatId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("body"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("filename"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("mediaId"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("mediaType"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("voice"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("caption"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("chatId"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("phone"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void SendFileRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_BodyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("body")), m_Body));
    }
    if(m_FilenameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("filename")), m_Filename));
    }
    if(m_MediaIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mediaId")), m_MediaId));
    }
    if(m_MediaTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mediaType")), fromMediaTypeEnum(m_MediaType)));
    }
    if(m_VoiceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("voice")), m_Voice));
    }
    if(m_CaptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("caption")), m_Caption));
    }
    if(m_QuotedMsgIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("quotedMsgId")), m_QuotedMsgId));
    }
    if(m_ChatIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("chatId")), m_ChatId));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
}

bool SendFileRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        utility::string_t refVal_setBody;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("body"))), refVal_setBody );
        setBody(refVal_setBody);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("filename"))))
    {
        utility::string_t refVal_setFilename;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("filename"))), refVal_setFilename );
        setFilename(refVal_setFilename);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mediaId"))))
    {
        utility::string_t refVal_setMediaId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mediaId"))), refVal_setMediaId );
        setMediaId(refVal_setMediaId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mediaType"))))
    {
        utility::string_t refVal_setMediaType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mediaType"))), refVal_setMediaType );
        setMediaType(toMediaTypeEnum(refVal_setMediaType));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("voice"))))
    {
        bool refVal_setVoice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("voice"))), refVal_setVoice );
        setVoice(refVal_setVoice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("caption"))))
    {
        utility::string_t refVal_setCaption;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("caption"))), refVal_setCaption );
        setCaption(refVal_setCaption);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))))
    {
        utility::string_t refVal_setQuotedMsgId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))), refVal_setQuotedMsgId );
        setQuotedMsgId(refVal_setQuotedMsgId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("chatId"))))
    {
        utility::string_t refVal_setChatId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("chatId"))), refVal_setChatId );
        setChatId(refVal_setChatId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        int32_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    return ok;
}

SendFileRequest::MediaTypeEnum SendFileRequest::toMediaTypeEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("image")) {
        return MediaTypeEnum::IMAGE;
    }
    
    if (value == utility::conversions::to_string_t("video")) {
        return MediaTypeEnum::VIDEO;
    }
    
    if (value == utility::conversions::to_string_t("audio")) {
        return MediaTypeEnum::AUDIO;
    }
    
    if (value == utility::conversions::to_string_t("document")) {
        return MediaTypeEnum::DOCUMENT;
    }
    
    throw std::invalid_argument("Invalid value for conversion to MediaTypeEnum");
}


const utility::string_t SendFileRequest::fromMediaTypeEnum(const MediaTypeEnum value) const
{
    switch(value)
    {
        
        case MediaTypeEnum::IMAGE: return utility::conversions::to_string_t("image");
        
        case MediaTypeEnum::VIDEO: return utility::conversions::to_string_t("video");
        
        case MediaTypeEnum::AUDIO: return utility::conversions::to_string_t("audio");
        
        case MediaTypeEnum::DOCUMENT: return utility::conversions::to_string_t("document");
        
    }
}


utility::string_t SendFileRequest::getBody() const
{
    return m_Body;
}


void SendFileRequest::setBody(const utility::string_t& value)
{
    m_Body = value;
    m_BodyIsSet = true;
}

bool SendFileRequest::bodyIsSet() const
{
    return m_BodyIsSet;
}

void SendFileRequest::unsetBody()
{
    m_BodyIsSet = false;
}
utility::string_t SendFileRequest::getFilename() const
{
    return m_Filename;
}


void SendFileRequest::setFilename(const utility::string_t& value)
{
    m_Filename = value;
    m_FilenameIsSet = true;
}

bool SendFileRequest::filenameIsSet() const
{
    return m_FilenameIsSet;
}

void SendFileRequest::unsetFilename()
{
    m_FilenameIsSet = false;
}
utility::string_t SendFileRequest::getMediaId() const
{
    return m_MediaId;
}


void SendFileRequest::setMediaId(const utility::string_t& value)
{
    m_MediaId = value;
    m_MediaIdIsSet = true;
}

bool SendFileRequest::mediaIdIsSet() const
{
    return m_MediaIdIsSet;
}

void SendFileRequest::unsetMediaId()
{
    m_MediaIdIsSet = false;
}
SendFileRequest::MediaTypeEnum SendFileRequest::getMediaType() const
{
    return m_MediaType;
}


void SendFileRequest::setMediaType(const MediaTypeEnum value)
{
    m_MediaType = value;
    m_MediaTypeIsSet = true;
}

bool SendFileRequest::mediaTypeIsSet() const
{
    return m_MediaTypeIsSet;
}

void SendFileRequest::unsetMediaType()
{
    m_MediaTypeIsSet = false;
}
bool SendFileRequest::isVoice() const
{
    return m_Voice;
}

void SendFileRequest::setVoice(bool value)
{
    m_Voice = value;
    m_VoiceIsSet = true;
}

bool SendFileRequest::voiceIsSet() const
{
    return m_VoiceIsSet;
}

void SendFileRequest::unsetVoice()
{
    m_VoiceIsSet = false;
}
utility::string_t SendFileRequest::getCaption() const
{
    return m_Caption;
}


void SendFileRequest::setCaption(const utility::string_t& value)
{
    m_Caption = value;
    m_CaptionIsSet = true;
}

bool SendFileRequest::captionIsSet() const
{
    return m_CaptionIsSet;
}

void SendFileRequest::unsetCaption()
{
    m_CaptionIsSet = false;
}
utility::string_t SendFileRequest::getQuotedMsgId() const
{
    return m_QuotedMsgId;
}


void SendFileRequest::setQuotedMsgId(const utility::string_t& value)
{
    m_QuotedMsgId = value;
    m_QuotedMsgIdIsSet = true;
}

bool SendFileRequest::quotedMsgIdIsSet() const
{
    return m_QuotedMsgIdIsSet;
}

void SendFileRequest::unsetQuotedMsgId()
{
    m_QuotedMsgIdIsSet = false;
}
utility::string_t SendFileRequest::getChatId() const
{
    return m_ChatId;
}


void SendFileRequest::setChatId(const utility::string_t& value)
{
    m_ChatId = value;
    m_ChatIdIsSet = true;
}

bool SendFileRequest::chatIdIsSet() const
{
    return m_ChatIdIsSet;
}

void SendFileRequest::unsetChatId()
{
    m_ChatIdIsSet = false;
}
int32_t SendFileRequest::getPhone() const
{
    return m_Phone;
}

void SendFileRequest::setPhone(int32_t value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SendFileRequest::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SendFileRequest::unsetPhone()
{
    m_PhoneIsSet = false;
}


std::map<utility::string_t, web::json::value> SendFileRequest::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void SendFileRequest::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void SendFileRequest::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool SendFileRequest::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void SendFileRequest::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


