/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/SendContact_request_contacts_inner_name.h"

namespace onemsg {
namespace chat {
namespace model {

SendContact_request_contacts_inner_name::SendContact_request_contacts_inner_name()
{
    m_Formatted_name = utility::conversions::to_string_t("");
    m_Formatted_nameIsSet = false;
    m_First_name = utility::conversions::to_string_t("");
    m_First_nameIsSet = false;
    m_Last_name = utility::conversions::to_string_t("");
    m_Last_nameIsSet = false;
    m_Middle_name = utility::conversions::to_string_t("");
    m_Middle_nameIsSet = false;
    m_Suffix = utility::conversions::to_string_t("");
    m_SuffixIsSet = false;
    m_Prefix = utility::conversions::to_string_t("");
    m_PrefixIsSet = false;
}

SendContact_request_contacts_inner_name::~SendContact_request_contacts_inner_name()
{
}

void SendContact_request_contacts_inner_name::validate()
{
    // TODO: implement validation
}

web::json::value SendContact_request_contacts_inner_name::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Formatted_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("formatted_name"))] = ModelBase::toJson(m_Formatted_name);
    }
    if(m_First_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("first_name"))] = ModelBase::toJson(m_First_name);
    }
    if(m_Last_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_name"))] = ModelBase::toJson(m_Last_name);
    }
    if(m_Middle_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("middle_name"))] = ModelBase::toJson(m_Middle_name);
    }
    if(m_SuffixIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("suffix"))] = ModelBase::toJson(m_Suffix);
    }
    if(m_PrefixIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("prefix"))] = ModelBase::toJson(m_Prefix);
    }

    return val;
}

bool SendContact_request_contacts_inner_name::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("formatted_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("formatted_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFormattedName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFormattedName);
            setFormattedName(refVal_setFormattedName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("first_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("first_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFirstName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFirstName);
            setFirstName(refVal_setFirstName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastName);
            setLastName(refVal_setLastName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("middle_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("middle_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMiddleName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMiddleName);
            setMiddleName(refVal_setMiddleName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("suffix"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("suffix")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSuffix;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSuffix);
            setSuffix(refVal_setSuffix);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("prefix"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("prefix")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPrefix;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrefix);
            setPrefix(refVal_setPrefix);
            
        }
    }
    return ok;
}

void SendContact_request_contacts_inner_name::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Formatted_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("formatted_name")), m_Formatted_name));
    }
    if(m_First_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("first_name")), m_First_name));
    }
    if(m_Last_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_name")), m_Last_name));
    }
    if(m_Middle_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("middle_name")), m_Middle_name));
    }
    if(m_SuffixIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("suffix")), m_Suffix));
    }
    if(m_PrefixIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("prefix")), m_Prefix));
    }
}

bool SendContact_request_contacts_inner_name::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("formatted_name"))))
    {
        utility::string_t refVal_setFormattedName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("formatted_name"))), refVal_setFormattedName );
        setFormattedName(refVal_setFormattedName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("first_name"))))
    {
        utility::string_t refVal_setFirstName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("first_name"))), refVal_setFirstName );
        setFirstName(refVal_setFirstName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_name"))))
    {
        utility::string_t refVal_setLastName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_name"))), refVal_setLastName );
        setLastName(refVal_setLastName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("middle_name"))))
    {
        utility::string_t refVal_setMiddleName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("middle_name"))), refVal_setMiddleName );
        setMiddleName(refVal_setMiddleName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("suffix"))))
    {
        utility::string_t refVal_setSuffix;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("suffix"))), refVal_setSuffix );
        setSuffix(refVal_setSuffix);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("prefix"))))
    {
        utility::string_t refVal_setPrefix;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("prefix"))), refVal_setPrefix );
        setPrefix(refVal_setPrefix);
    }
    return ok;
}


utility::string_t SendContact_request_contacts_inner_name::getFormattedName() const
{
    return m_Formatted_name;
}


void SendContact_request_contacts_inner_name::setFormattedName(const utility::string_t& value)
{
    m_Formatted_name = value;
    m_Formatted_nameIsSet = true;
}

bool SendContact_request_contacts_inner_name::formattedNameIsSet() const
{
    return m_Formatted_nameIsSet;
}

void SendContact_request_contacts_inner_name::unsetFormatted_name()
{
    m_Formatted_nameIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_name::getFirstName() const
{
    return m_First_name;
}


void SendContact_request_contacts_inner_name::setFirstName(const utility::string_t& value)
{
    m_First_name = value;
    m_First_nameIsSet = true;
}

bool SendContact_request_contacts_inner_name::firstNameIsSet() const
{
    return m_First_nameIsSet;
}

void SendContact_request_contacts_inner_name::unsetFirst_name()
{
    m_First_nameIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_name::getLastName() const
{
    return m_Last_name;
}


void SendContact_request_contacts_inner_name::setLastName(const utility::string_t& value)
{
    m_Last_name = value;
    m_Last_nameIsSet = true;
}

bool SendContact_request_contacts_inner_name::lastNameIsSet() const
{
    return m_Last_nameIsSet;
}

void SendContact_request_contacts_inner_name::unsetLast_name()
{
    m_Last_nameIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_name::getMiddleName() const
{
    return m_Middle_name;
}


void SendContact_request_contacts_inner_name::setMiddleName(const utility::string_t& value)
{
    m_Middle_name = value;
    m_Middle_nameIsSet = true;
}

bool SendContact_request_contacts_inner_name::middleNameIsSet() const
{
    return m_Middle_nameIsSet;
}

void SendContact_request_contacts_inner_name::unsetMiddle_name()
{
    m_Middle_nameIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_name::getSuffix() const
{
    return m_Suffix;
}


void SendContact_request_contacts_inner_name::setSuffix(const utility::string_t& value)
{
    m_Suffix = value;
    m_SuffixIsSet = true;
}

bool SendContact_request_contacts_inner_name::suffixIsSet() const
{
    return m_SuffixIsSet;
}

void SendContact_request_contacts_inner_name::unsetSuffix()
{
    m_SuffixIsSet = false;
}
utility::string_t SendContact_request_contacts_inner_name::getPrefix() const
{
    return m_Prefix;
}


void SendContact_request_contacts_inner_name::setPrefix(const utility::string_t& value)
{
    m_Prefix = value;
    m_PrefixIsSet = true;
}

bool SendContact_request_contacts_inner_name::prefixIsSet() const
{
    return m_PrefixIsSet;
}

void SendContact_request_contacts_inner_name::unsetPrefix()
{
    m_PrefixIsSet = false;
}

}
}
}


