/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendButton_request_sections_inner_reply.h"

namespace onemsg {
namespace sdk {
namespace model {

SendButton_request_sections_inner_reply::SendButton_request_sections_inner_reply()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
}

SendButton_request_sections_inner_reply::~SendButton_request_sections_inner_reply()
{
}

void SendButton_request_sections_inner_reply::validate()
{
    // TODO: implement validation
}

web::json::value SendButton_request_sections_inner_reply::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }

    return val;
}

bool SendButton_request_sections_inner_reply::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    return ok;
}

void SendButton_request_sections_inner_reply::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
}

bool SendButton_request_sections_inner_reply::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    return ok;
}


utility::string_t SendButton_request_sections_inner_reply::getId() const
{
    return m_Id;
}


void SendButton_request_sections_inner_reply::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool SendButton_request_sections_inner_reply::idIsSet() const
{
    return m_IdIsSet;
}

void SendButton_request_sections_inner_reply::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t SendButton_request_sections_inner_reply::getTitle() const
{
    return m_Title;
}


void SendButton_request_sections_inner_reply::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool SendButton_request_sections_inner_reply::titleIsSet() const
{
    return m_TitleIsSet;
}

void SendButton_request_sections_inner_reply::unsetTitle()
{
    m_TitleIsSet = false;
}

}
}
}


