/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendSticker_request.h"

namespace onemsg {
namespace chat {
namespace model {

SendSticker_request::SendSticker_request()
{
    m_Phone = 0;
    m_PhoneIsSet = false;
    m_ChatId = utility::conversions::to_string_t("");
    m_ChatIdIsSet = false;
    m_MediaId = utility::conversions::to_string_t("");
    m_MediaIdIsSet = false;
    m_Link = utility::conversions::to_string_t("");
    m_LinkIsSet = false;
    m_QuotedMsgId = utility::conversions::to_string_t("");
    m_QuotedMsgIdIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

SendSticker_request::~SendSticker_request()
{
}

void SendSticker_request::validate()
{
    // TODO: implement validation
}

web::json::value SendSticker_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PhoneIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_ChatIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("chatId"))] = ModelBase::toJson(m_ChatId);
    }
    if(m_MediaIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("mediaId"))] = ModelBase::toJson(m_MediaId);
    }
    if(m_LinkIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("link"))] = ModelBase::toJson(m_Link);
    }
    if(m_QuotedMsgIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))] = ModelBase::toJson(m_QuotedMsgId);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool SendSticker_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("chatId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("chatId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setChatId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChatId);
            setChatId(refVal_setChatId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mediaId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mediaId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMediaId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMediaId);
            setMediaId(refVal_setMediaId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("link"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("link")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLink;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLink);
            setLink(refVal_setLink);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setQuotedMsgId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuotedMsgId);
            setQuotedMsgId(refVal_setQuotedMsgId);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("phone"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("chatId"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("mediaId"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("link"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void SendSticker_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_ChatIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("chatId")), m_ChatId));
    }
    if(m_MediaIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mediaId")), m_MediaId));
    }
    if(m_LinkIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("link")), m_Link));
    }
    if(m_QuotedMsgIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("quotedMsgId")), m_QuotedMsgId));
    }
}

bool SendSticker_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        int32_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("chatId"))))
    {
        utility::string_t refVal_setChatId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("chatId"))), refVal_setChatId );
        setChatId(refVal_setChatId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mediaId"))))
    {
        utility::string_t refVal_setMediaId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mediaId"))), refVal_setMediaId );
        setMediaId(refVal_setMediaId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("link"))))
    {
        utility::string_t refVal_setLink;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("link"))), refVal_setLink );
        setLink(refVal_setLink);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))))
    {
        utility::string_t refVal_setQuotedMsgId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("quotedMsgId"))), refVal_setQuotedMsgId );
        setQuotedMsgId(refVal_setQuotedMsgId);
    }
    return ok;
}


int32_t SendSticker_request::getPhone() const
{
    return m_Phone;
}

void SendSticker_request::setPhone(int32_t value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SendSticker_request::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SendSticker_request::unsetPhone()
{
    m_PhoneIsSet = false;
}
utility::string_t SendSticker_request::getChatId() const
{
    return m_ChatId;
}


void SendSticker_request::setChatId(const utility::string_t& value)
{
    m_ChatId = value;
    m_ChatIdIsSet = true;
}

bool SendSticker_request::chatIdIsSet() const
{
    return m_ChatIdIsSet;
}

void SendSticker_request::unsetChatId()
{
    m_ChatIdIsSet = false;
}
utility::string_t SendSticker_request::getMediaId() const
{
    return m_MediaId;
}


void SendSticker_request::setMediaId(const utility::string_t& value)
{
    m_MediaId = value;
    m_MediaIdIsSet = true;
}

bool SendSticker_request::mediaIdIsSet() const
{
    return m_MediaIdIsSet;
}

void SendSticker_request::unsetMediaId()
{
    m_MediaIdIsSet = false;
}
utility::string_t SendSticker_request::getLink() const
{
    return m_Link;
}


void SendSticker_request::setLink(const utility::string_t& value)
{
    m_Link = value;
    m_LinkIsSet = true;
}

bool SendSticker_request::linkIsSet() const
{
    return m_LinkIsSet;
}

void SendSticker_request::unsetLink()
{
    m_LinkIsSet = false;
}
utility::string_t SendSticker_request::getQuotedMsgId() const
{
    return m_QuotedMsgId;
}


void SendSticker_request::setQuotedMsgId(const utility::string_t& value)
{
    m_QuotedMsgId = value;
    m_QuotedMsgIdIsSet = true;
}

bool SendSticker_request::quotedMsgIdIsSet() const
{
    return m_QuotedMsgIdIsSet;
}

void SendSticker_request::unsetQuotedMsgId()
{
    m_QuotedMsgIdIsSet = false;
}


std::map<utility::string_t, web::json::value> SendSticker_request::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void SendSticker_request::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void SendSticker_request::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool SendSticker_request::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void SendSticker_request::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


