/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendOrderDetails_request_order.h"

namespace onemsg {
namespace chat {
namespace model {

SendOrderDetails_request_order::SendOrderDetails_request_order()
{
    m_Status = utility::conversions::to_string_t("");
    m_StatusIsSet = false;
    m_ItemsIsSet = false;
    m_SubtotalIsSet = false;
    m_TaxIsSet = false;
    m_ShippingIsSet = false;
    m_DiscountIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

SendOrderDetails_request_order::~SendOrderDetails_request_order()
{
}

void SendOrderDetails_request_order::validate()
{
    // TODO: implement validation
}

web::json::value SendOrderDetails_request_order::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_ItemsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("items"))] = ModelBase::toJson(m_Items);
    }
    if(m_SubtotalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subtotal"))] = ModelBase::toJson(m_Subtotal);
    }
    if(m_TaxIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tax"))] = ModelBase::toJson(m_Tax);
    }
    if(m_ShippingIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("shipping"))] = ModelBase::toJson(m_Shipping);
    }
    if(m_DiscountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("discount"))] = ModelBase::toJson(m_Discount);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool SendOrderDetails_request_order::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("items"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("items")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SendOrderDetails_request_order_items_inner>> refVal_setItems;
            ok &= ModelBase::fromJson(fieldValue, refVal_setItems);
            setItems(refVal_setItems);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subtotal"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subtotal")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SendOrderDetails_request_order_items_inner_amount> refVal_setSubtotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubtotal);
            setSubtotal(refVal_setSubtotal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tax"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tax")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setTax;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTax);
            setTax(refVal_setTax);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shipping"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shipping")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setShipping;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShipping);
            setShipping(refVal_setShipping);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("discount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("discount")));
        if(!fieldValue.is_null())
        {
            std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setDiscount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDiscount);
            setDiscount(refVal_setDiscount);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("status"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("items"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("subtotal"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("tax"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("shipping"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("discount"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void SendOrderDetails_request_order::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_ItemsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("items")), m_Items));
    }
    if(m_SubtotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subtotal")), m_Subtotal));
    }
    if(m_TaxIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tax")), m_Tax));
    }
    if(m_ShippingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shipping")), m_Shipping));
    }
    if(m_DiscountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("discount")), m_Discount));
    }
}

bool SendOrderDetails_request_order::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("items"))))
    {
        std::vector<std::shared_ptr<SendOrderDetails_request_order_items_inner>> refVal_setItems;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("items"))), refVal_setItems );
        setItems(refVal_setItems);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subtotal"))))
    {
        std::shared_ptr<SendOrderDetails_request_order_items_inner_amount> refVal_setSubtotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subtotal"))), refVal_setSubtotal );
        setSubtotal(refVal_setSubtotal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tax"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setTax;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tax"))), refVal_setTax );
        setTax(refVal_setTax);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shipping"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setShipping;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shipping"))), refVal_setShipping );
        setShipping(refVal_setShipping);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("discount"))))
    {
        std::map<utility::string_t, std::shared_ptr<AnyType>> refVal_setDiscount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("discount"))), refVal_setDiscount );
        setDiscount(refVal_setDiscount);
    }
    return ok;
}


utility::string_t SendOrderDetails_request_order::getStatus() const
{
    return m_Status;
}


void SendOrderDetails_request_order::setStatus(const utility::string_t& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool SendOrderDetails_request_order::statusIsSet() const
{
    return m_StatusIsSet;
}

void SendOrderDetails_request_order::unsetStatus()
{
    m_StatusIsSet = false;
}
std::vector<std::shared_ptr<SendOrderDetails_request_order_items_inner>> SendOrderDetails_request_order::getItems() const
{
    return m_Items;
}


void SendOrderDetails_request_order::setItems(const std::vector<std::shared_ptr<SendOrderDetails_request_order_items_inner>>& value)
{
    m_Items = value;
    m_ItemsIsSet = true;
}

bool SendOrderDetails_request_order::itemsIsSet() const
{
    return m_ItemsIsSet;
}

void SendOrderDetails_request_order::unsetItems()
{
    m_ItemsIsSet = false;
}
std::shared_ptr<SendOrderDetails_request_order_items_inner_amount> SendOrderDetails_request_order::getSubtotal() const
{
    return m_Subtotal;
}


void SendOrderDetails_request_order::setSubtotal(const std::shared_ptr<SendOrderDetails_request_order_items_inner_amount>& value)
{
    m_Subtotal = value;
    m_SubtotalIsSet = true;
}

bool SendOrderDetails_request_order::subtotalIsSet() const
{
    return m_SubtotalIsSet;
}

void SendOrderDetails_request_order::unsetSubtotal()
{
    m_SubtotalIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> SendOrderDetails_request_order::getTax() const
{
    return m_Tax;
}


void SendOrderDetails_request_order::setTax(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Tax = value;
    m_TaxIsSet = true;
}

bool SendOrderDetails_request_order::taxIsSet() const
{
    return m_TaxIsSet;
}

void SendOrderDetails_request_order::unsetTax()
{
    m_TaxIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> SendOrderDetails_request_order::getShipping() const
{
    return m_Shipping;
}


void SendOrderDetails_request_order::setShipping(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Shipping = value;
    m_ShippingIsSet = true;
}

bool SendOrderDetails_request_order::shippingIsSet() const
{
    return m_ShippingIsSet;
}

void SendOrderDetails_request_order::unsetShipping()
{
    m_ShippingIsSet = false;
}
std::map<utility::string_t, std::shared_ptr<AnyType>> SendOrderDetails_request_order::getDiscount() const
{
    return m_Discount;
}


void SendOrderDetails_request_order::setDiscount(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value)
{
    m_Discount = value;
    m_DiscountIsSet = true;
}

bool SendOrderDetails_request_order::discountIsSet() const
{
    return m_DiscountIsSet;
}

void SendOrderDetails_request_order::unsetDiscount()
{
    m_DiscountIsSet = false;
}


std::map<utility::string_t, web::json::value> SendOrderDetails_request_order::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void SendOrderDetails_request_order::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void SendOrderDetails_request_order::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool SendOrderDetails_request_order::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void SendOrderDetails_request_order::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


