/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendList_request_sections_inner.h"

namespace onemsg {
namespace sdk {
namespace model {

SendList_request_sections_inner::SendList_request_sections_inner()
{
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_RowsIsSet = false;
}

SendList_request_sections_inner::~SendList_request_sections_inner()
{
}

void SendList_request_sections_inner::validate()
{
    // TODO: implement validation
}

web::json::value SendList_request_sections_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_RowsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("rows"))] = ModelBase::toJson(m_Rows);
    }

    return val;
}

bool SendList_request_sections_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rows"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rows")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SendList_request_sections_inner_rows_inner>> refVal_setRows;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRows);
            setRows(refVal_setRows);
            
        }
    }
    return ok;
}

void SendList_request_sections_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_RowsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rows")), m_Rows));
    }
}

bool SendList_request_sections_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rows"))))
    {
        std::vector<std::shared_ptr<SendList_request_sections_inner_rows_inner>> refVal_setRows;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rows"))), refVal_setRows );
        setRows(refVal_setRows);
    }
    return ok;
}


utility::string_t SendList_request_sections_inner::getTitle() const
{
    return m_Title;
}


void SendList_request_sections_inner::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool SendList_request_sections_inner::titleIsSet() const
{
    return m_TitleIsSet;
}

void SendList_request_sections_inner::unsetTitle()
{
    m_TitleIsSet = false;
}
std::vector<std::shared_ptr<SendList_request_sections_inner_rows_inner>> SendList_request_sections_inner::getRows() const
{
    return m_Rows;
}


void SendList_request_sections_inner::setRows(const std::vector<std::shared_ptr<SendList_request_sections_inner_rows_inner>>& value)
{
    m_Rows = value;
    m_RowsIsSet = true;
}

bool SendList_request_sections_inner::rowsIsSet() const
{
    return m_RowsIsSet;
}

void SendList_request_sections_inner::unsetRows()
{
    m_RowsIsSet = false;
}

}
}
}


