/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-chat-api/model/SendFlow_request_header.h"

namespace onemsg {
namespace chat {
namespace model {

void SendFlow_request_header::validate()
{
    // TODO: implement validation
}

const SendFlow_request_header::VariantType& SendFlow_request_header::getVariant() const
{
    return m_variantValue;
}

void SendFlow_request_header::setVariant(SendFlow_request_header::VariantType value)
{
    m_variantValue = value;
}

web::json::value SendFlow_request_header::toJson() const
{
    web::json::value val = web::json::value::object();

    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
            val = web::json::value::null();
        } else {
            val = arg.toJson();
        }
    }, m_variantValue);

    return val;
}

void SendFlow_request_header::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (!std::is_same_v<T, std::monostate>) {
          arg.toMultipart(multipart, prefix);
        }
    }, m_variantValue);
}

template bool SendFlow_request_header::fromJson<std::shared_ptr&lt;Object&gt;>(const web::json::value& json);
template bool SendFlow_request_header::fromMultiPart<std::shared_ptr&lt;Object&gt;>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool SendFlow_request_header::fromJson<utility::string_t>(const web::json::value& json);
template bool SendFlow_request_header::fromMultiPart<utility::string_t>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);

}
}
}


