/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/SendButton_request_sections_inner.h"

namespace onemsg {
namespace sdk {
namespace model {

SendButton_request_sections_inner::SendButton_request_sections_inner()
{
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
    m_ReplyIsSet = false;
}

SendButton_request_sections_inner::~SendButton_request_sections_inner()
{
}

void SendButton_request_sections_inner::validate()
{
    // TODO: implement validation
}

web::json::value SendButton_request_sections_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TypeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type);
    }
    if(m_ReplyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("reply"))] = ModelBase::toJson(m_Reply);
    }

    return val;
}

bool SendButton_request_sections_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reply"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reply")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SendButton_request_sections_inner_reply> refVal_setReply;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReply);
            setReply(refVal_setReply);
            
        }
    }
    return ok;
}

void SendButton_request_sections_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type));
    }
    if(m_ReplyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reply")), m_Reply));
    }
}

bool SendButton_request_sections_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reply"))))
    {
        std::shared_ptr<SendButton_request_sections_inner_reply> refVal_setReply;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reply"))), refVal_setReply );
        setReply(refVal_setReply);
    }
    return ok;
}


utility::string_t SendButton_request_sections_inner::getType() const
{
    return m_Type;
}


void SendButton_request_sections_inner::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool SendButton_request_sections_inner::typeIsSet() const
{
    return m_TypeIsSet;
}

void SendButton_request_sections_inner::unsetType()
{
    m_TypeIsSet = false;
}
std::shared_ptr<SendButton_request_sections_inner_reply> SendButton_request_sections_inner::getReply() const
{
    return m_Reply;
}


void SendButton_request_sections_inner::setReply(const std::shared_ptr<SendButton_request_sections_inner_reply>& value)
{
    m_Reply = value;
    m_ReplyIsSet = true;
}

bool SendButton_request_sections_inner::replyIsSet() const
{
    return m_ReplyIsSet;
}

void SendButton_request_sections_inner::unsetReply()
{
    m_ReplyIsSet = false;
}

}
}
}


