/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "one-msg-sdk/model/UpdateCallingSettings_200_response.h"

namespace onemsg {
namespace sdk {
namespace model {

UpdateCallingSettings_200_response::UpdateCallingSettings_200_response()
{
    m_Success = false;
    m_SuccessIsSet = false;
    m_Result = utility::conversions::to_string_t("");
    m_ResultIsSet = false;
    m_ResponseIsSet = false;
    m_AdditionalPropertiesIsSet = false;
}

UpdateCallingSettings_200_response::~UpdateCallingSettings_200_response()
{
}

void UpdateCallingSettings_200_response::validate()
{
    // TODO: implement validation
}

web::json::value UpdateCallingSettings_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SuccessIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("success"))] = ModelBase::toJson(m_Success);
    }
    if(m_ResultIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("result"))] = ModelBase::toJson(m_Result);
    }
    if(m_ResponseIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("response"))] = ModelBase::toJson(m_Response);
    }
    // Serialize additional properties
    if(m_AdditionalPropertiesIsSet)
    {
        for(const auto& item : m_AdditionalProperties)
        {
            val[item.first] = item.second;
        }
    }

    return val;
}

bool UpdateCallingSettings_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("success")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSuccess;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSuccess);
            setSuccess(refVal_setSuccess);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("result"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("result")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setResult;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResult);
            setResult(refVal_setResult);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("response"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("response")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<UpdateCallingSettings_200_response_response> refVal_setResponse;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResponse);
            setResponse(refVal_setResponse);
            
        }
    }
    // Capture additional properties (keys not defined in the schema)
    if(val.is_object())
    {
        for(const auto& item : val.as_object())
        {
            // Skip known properties
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("success"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("result"))) continue;
            if(item.first == utility::conversions::to_string_t(_XPLATSTR("response"))) continue;
            // This is an additional property
            m_AdditionalProperties[item.first] = item.second;
            m_AdditionalPropertiesIsSet = true;
        }
    }
    return ok;
}

void UpdateCallingSettings_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SuccessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("success")), m_Success));
    }
    if(m_ResultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("result")), m_Result));
    }
    if(m_ResponseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("response")), m_Response));
    }
}

bool UpdateCallingSettings_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        bool refVal_setSuccess;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("success"))), refVal_setSuccess );
        setSuccess(refVal_setSuccess);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("result"))))
    {
        utility::string_t refVal_setResult;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("result"))), refVal_setResult );
        setResult(refVal_setResult);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("response"))))
    {
        std::shared_ptr<UpdateCallingSettings_200_response_response> refVal_setResponse;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("response"))), refVal_setResponse );
        setResponse(refVal_setResponse);
    }
    return ok;
}


bool UpdateCallingSettings_200_response::isSuccess() const
{
    return m_Success;
}

void UpdateCallingSettings_200_response::setSuccess(bool value)
{
    m_Success = value;
    m_SuccessIsSet = true;
}

bool UpdateCallingSettings_200_response::successIsSet() const
{
    return m_SuccessIsSet;
}

void UpdateCallingSettings_200_response::unsetSuccess()
{
    m_SuccessIsSet = false;
}
utility::string_t UpdateCallingSettings_200_response::getResult() const
{
    return m_Result;
}


void UpdateCallingSettings_200_response::setResult(const utility::string_t& value)
{
    m_Result = value;
    m_ResultIsSet = true;
}

bool UpdateCallingSettings_200_response::resultIsSet() const
{
    return m_ResultIsSet;
}

void UpdateCallingSettings_200_response::unsetResult()
{
    m_ResultIsSet = false;
}
std::shared_ptr<UpdateCallingSettings_200_response_response> UpdateCallingSettings_200_response::getResponse() const
{
    return m_Response;
}


void UpdateCallingSettings_200_response::setResponse(const std::shared_ptr<UpdateCallingSettings_200_response_response>& value)
{
    m_Response = value;
    m_ResponseIsSet = true;
}

bool UpdateCallingSettings_200_response::responseIsSet() const
{
    return m_ResponseIsSet;
}

void UpdateCallingSettings_200_response::unsetResponse()
{
    m_ResponseIsSet = false;
}


std::map<utility::string_t, web::json::value> UpdateCallingSettings_200_response::getAdditionalProperties() const
{
    return m_AdditionalProperties;
}

void UpdateCallingSettings_200_response::setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value)
{
    m_AdditionalProperties = value;
    m_AdditionalPropertiesIsSet = true;
}

void UpdateCallingSettings_200_response::addAdditionalProperty(const utility::string_t& key, const web::json::value& value)
{
    m_AdditionalProperties[key] = value;
    m_AdditionalPropertiesIsSet = true;
}

bool UpdateCallingSettings_200_response::additionalPropertiesIsSet() const
{
    return m_AdditionalPropertiesIsSet;
}

void UpdateCallingSettings_200_response::unsetAdditionalProperties()
{
    m_AdditionalProperties.clear();
    m_AdditionalPropertiesIsSet = false;
}
}
}
}


