/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CallingApi.h
 *
 * 
 */

#ifndef ONEMSG_CHAT_API_CallingApi_H_
#define ONEMSG_CHAT_API_CallingApi_H_



#include "one-msg-sdk/ApiClient.h"

#include "one-msg-sdk/AnyType.h"
#include "one-msg-sdk/model/ErrorResponse.h"
#include <map>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace onemsg {
namespace chat {
namespace api {

using namespace onemsg::chat::model;



class  CallingApi 
{
public:

    explicit CallingApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CallingApi();

    /// <summary>
    /// Get calling settings
    /// </summary>
    /// <remarks>
    /// WhatsApp Calling API settings (beta). Requires Meta Calling enablement on the WABA. Not production-complete — paths and webhook field names may change. Trial/subscription-limited channels are blocked. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> getCallingSettings(
        utility::string_t token
    ) const;
    /// <summary>
    /// Initiate WhatsApp call
    /// </summary>
    /// <remarks>
    /// Outbound Calling API (beta). Requires Meta Calling enablement and product consent. Not production-complete — verify on stage before relying on this in production. Trial/subscription-limited channels are blocked. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    /// <param name="requestBody"> (optional)</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> initiateCall(
        utility::string_t token,
        boost::optional<std::map<utility::string_t, std::shared_ptr<AnyType>>> requestBody
    ) const;
    /// <summary>
    /// Update calling settings
    /// </summary>
    /// <remarks>
    /// Update WhatsApp Calling API settings (beta). Requires Meta Calling enablement. Trial/subscription-limited channels are blocked. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    /// <param name="requestBody"> (optional)</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> updateCallingSettings(
        utility::string_t token,
        boost::optional<std::map<utility::string_t, std::shared_ptr<AnyType>>> requestBody
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}

#endif /* ONEMSG_CHAT_API_CallingApi_H_ */

