/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CallingApi.h
 *
 * 
 */

#ifndef ONEMSG_SDK_API_CallingApi_H_
#define ONEMSG_SDK_API_CallingApi_H_



#include "one-msg-sdk/ApiClient.h"

#include "one-msg-sdk/model/CallingSettings.h"
#include "one-msg-sdk/model/ErrorResponse.h"
#include "one-msg-sdk/model/InitiateCallRequest.h"
#include "one-msg-sdk/model/InitiateCallResponse.h"
#include "one-msg-sdk/model/UpdateCallingSettings_200_response.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace onemsg {
namespace sdk {
namespace api {

using namespace onemsg::sdk::model;



class  CallingApi 
{
public:

    explicit CallingApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~CallingApi();

    /// <summary>
    /// Get calling settings
    /// </summary>
    /// <remarks>
    /// Return WhatsApp Calling API settings for this channel (beta).  Proxies upstream &#x60;GET /calling/settings&#x60;.  **Prerequisites** - Number must be eligible for Meta Calling (Cloud API; not COEX) - Trial / &#x60;subscriptionBlocked&#x60; channels receive **403** plain text - You need your own WebRTC or SIP stack; 1msg is a **signaling proxy** only   and does **not** store call history or recordings  See the **Calling** tag overview for inbound/outbound flows and webhooks. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    pplx::task<std::shared_ptr<CallingSettings>> getCallingSettings(
        utility::string_t token
    ) const;
    /// <summary>
    /// Call action (connect / pre_accept / accept / reject / terminate)
    /// </summary>
    /// <remarks>
    /// Perform a WhatsApp Calling action (beta).  Proxies upstream &#x60;POST /calling/calls&#x60;. Despite the historical path name &#x60;/initiateCall&#x60;, this endpoint handles **all** call actions:  | action | Use | Required | |--------|-----|----------| | &#x60;connect&#x60; | Outbound business → user | &#x60;to&#x60; + &#x60;session&#x60; (&#x60;sdp_type: offer&#x60;) | | &#x60;pre_accept&#x60; | Inbound (optional, reduces audio clipping) | &#x60;call_id&#x60; + &#x60;session&#x60; (&#x60;sdp_type: answer&#x60;) | | &#x60;accept&#x60; | Inbound answer | &#x60;call_id&#x60; + &#x60;session&#x60; (&#x60;sdp_type: answer&#x60;) | | &#x60;reject&#x60; | Decline inbound | &#x60;call_id&#x60; | | &#x60;terminate&#x60; | Hang up | &#x60;call_id&#x60; |  **SDP / media (critical)** - &#x60;accept&#x60; / &#x60;pre_accept&#x60; require a **WebRTC-generated SDP answer**. - Do **not** send Meta&#39;s offer SDP back as the answer. - Postman (or curl) alone **cannot** establish real media — you need a   WebRTC or SIP stack. 1msg only proxies signaling.  Answer within ~**30–60 seconds** of an inbound &#x60;connect&#x60; webhook or Meta terminates as unanswered. Common Meta errors include Calling not enabled (&#x60;138000&#x60;), no permission (&#x60;138006&#x60;), SDP validation failures.  **Outbound** requires a prior Call Permission Request (CPR) acceptance. See the **Calling** tag overview for the full outbound flow and CPR limits.  Trial / &#x60;subscriptionBlocked&#x60; → **403** plain text. Upstream failures often return HTTP 200 with &#x60;{ \&quot;response\&quot;: { \&quot;error\&quot;: \&quot;...\&quot; } }&#x60;. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    /// <param name="initiateCallRequest"></param>
    pplx::task<std::shared_ptr<InitiateCallResponse>> initiateCall(
        utility::string_t token,
        std::shared_ptr<InitiateCallRequest> initiateCallRequest
    ) const;
    /// <summary>
    /// Update calling settings
    /// </summary>
    /// <remarks>
    /// Enable, disable, or update WhatsApp Calling settings (beta).  Proxies upstream &#x60;POST /calling/settings&#x60;. Body is forwarded as-is (1msg does not validate fields).  **Common fields under &#x60;calling&#x60;** - &#x60;status&#x60; (&#x60;ENABLED&#x60; | &#x60;DISABLED&#x60;) — required to turn calling on/off - &#x60;call_icon_visibility&#x60; (&#x60;DEFAULT&#x60; | &#x60;DISABLE_ALL&#x60;) — optional - &#x60;callback_permission_status&#x60; (&#x60;ENABLED&#x60; | &#x60;DISABLED&#x60;) — optional;   when enabled, inbound user calls grant callback permission - &#x60;call_hours&#x60; — optional hours / timezone object - &#x60;sip&#x60; — optional SIP trunk; when SIP is ENABLED, Graph call actions and   calling webhooks are not used - &#x60;srtp_key_exchange_protocol&#x60; (&#x60;DTLS&#x60; | &#x60;SDES&#x60;) — SDES only with SIP - &#x60;video.status&#x60; — optional  Meta may accept only one feature group per request — prefer focused updates (e.g. enable status first, then SIP).  Trial / &#x60;subscriptionBlocked&#x60; → **403** plain text. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    /// <param name="callingSettings"></param>
    pplx::task<std::shared_ptr<UpdateCallingSettings_200_response>> updateCallingSettings(
        utility::string_t token,
        std::shared_ptr<CallingSettings> callingSettings
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}

#endif /* ONEMSG_SDK_API_CallingApi_H_ */

