/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UsersApi.h
 *
 * 
 */

#ifndef ONEMSG_SDK_API_UsersApi_H_
#define ONEMSG_SDK_API_UsersApi_H_



#include "one-msg-sdk/ApiClient.h"

#include "one-msg-sdk/model/BlockUser_request.h"
#include "one-msg-sdk/model/ErrorResponse.h"
#include "one-msg-sdk/model/ListBlockedUsers_200_response.h"
#include "one-msg-sdk/model/SuccessResponse.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace onemsg {
namespace sdk {
namespace api {

using namespace onemsg::sdk::model;



class  UsersApi 
{
public:

    explicit UsersApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~UsersApi();

    /// <summary>
    /// Block WhatsApp user
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    /// <param name="blockUserRequest"></param>
    pplx::task<std::shared_ptr<SuccessResponse>> blockUser(
        utility::string_t token,
        std::shared_ptr<BlockUser_request> blockUserRequest
    ) const;
    /// <summary>
    /// List blocked WhatsApp users
    /// </summary>
    /// <remarks>
    /// Returns users currently blocked on this WhatsApp channel (WABA &#x60;GET /block_users&#x60;). Same channel token auth as &#x60;blockUser&#x60; / &#x60;unblockUser&#x60;. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    pplx::task<std::shared_ptr<ListBlockedUsers_200_response>> listBlockedUsers(
        utility::string_t token
    ) const;
    /// <summary>
    /// Unblock WhatsApp user
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    /// <param name="blockUserRequest"></param>
    pplx::task<std::shared_ptr<SuccessResponse>> unblockUser(
        utility::string_t token,
        std::shared_ptr<BlockUser_request> blockUserRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}

#endif /* ONEMSG_SDK_API_UsersApi_H_ */

