/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WebhooksApi.h
 *
 * 
 */

#ifndef ONEMSG_SDK_API_WebhooksApi_H_
#define ONEMSG_SDK_API_WebhooksApi_H_



#include "one-msg-sdk/ApiClient.h"

#include "one-msg-sdk/AnyType.h"
#include "one-msg-sdk/model/ErrorResponse.h"
#include "one-msg-sdk/model/GetWebhook_200_response.h"
#include <map>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace onemsg {
namespace sdk {
namespace api {

using namespace onemsg::sdk::model;



class  WebhooksApi 
{
public:

    explicit WebhooksApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~WebhooksApi();

    /// <summary>
    /// Get webhook URL
    /// </summary>
    /// <remarks>
    /// Returns the configured client webhook URL for this channel.
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    pplx::task<std::shared_ptr<GetWebhook_200_response>> getWebhook(
        utility::string_t token
    ) const;
    /// <summary>
    /// Set webhook URL
    /// </summary>
    /// <remarks>
    /// Configure the client webhook URL for inbound events.  WhatsApp **Calling** events (&#x60;field&#x3D;calls&#x60;) are forwarded as passthrough payloads with &#x60;type: \&quot;calls\&quot;&#x60; and &#x60;instanceId&#x60; (connect / status / terminate). Call permission replies arrive on the normal messages path (&#x60;call_permission_reply&#x60;). Details: **Calling** tag. 
    /// </remarks>
    /// <param name="token">JWT token or API key for authorization</param>
    /// <param name="getWebhook200Response"> (optional)</param>
    pplx::task<std::map<utility::string_t, std::shared_ptr<AnyType>>> setWebhook(
        utility::string_t token,
        boost::optional<std::shared_ptr<GetWebhook_200_response>> getWebhook200Response
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}

#endif /* ONEMSG_SDK_API_WebhooksApi_H_ */

