/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CallingSettings_calling_sip_servers_inner.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_CallingSettings_calling_sip_servers_inner_H_
#define ONEMSG_SDK_MODEL_CallingSettings_calling_sip_servers_inner_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace sdk {
namespace model {



class  CallingSettings_calling_sip_servers_inner
    : public ModelBase
{
public:
    CallingSettings_calling_sip_servers_inner();
    virtual ~CallingSettings_calling_sip_servers_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CallingSettings_calling_sip_servers_inner members


    utility::string_t getHostname() const;
    bool hostnameIsSet() const;
    void unsetHostname();
    void setHostname(const utility::string_t& value);

    int32_t getPort() const;
    bool portIsSet() const;
    void unsetPort();
    void setPort(int32_t value);

    std::map<utility::string_t, utility::string_t> getRequestUriUserParams() const;
    bool requestUriUserParamsIsSet() const;
    void unsetRequest_uri_user_params();
    void setRequestUriUserParams(const std::map<utility::string_t, utility::string_t>& value);

    /// <summary>
    /// Present on GET when SIP credentials are returned by Meta
    /// </summary>
    utility::string_t getSipUserPassword() const;
    bool sipUserPasswordIsSet() const;
    void unsetSip_user_password();
    void setSipUserPassword(const utility::string_t& value);

    /// <summary>
    /// Alternate password field name from some Meta responses
    /// </summary>
    utility::string_t getPassword() const;
    bool passwordIsSet() const;
    void unsetPassword();
    void setPassword(const utility::string_t& value);

    utility::string_t getAppId() const;
    bool appIdIsSet() const;
    void unsetApp_id();
    void setAppId(const utility::string_t& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    utility::string_t m_Hostname;
    bool m_HostnameIsSet;

    int32_t m_Port;
    bool m_PortIsSet;

    std::map<utility::string_t, utility::string_t> m_Request_uri_user_params;
    bool m_Request_uri_user_paramsIsSet;

    utility::string_t m_Sip_user_password;
    bool m_Sip_user_passwordIsSet;

    utility::string_t m_Password;
    bool m_PasswordIsSet;

    utility::string_t m_App_id;
    bool m_App_idIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_CallingSettings_calling_sip_servers_inner_H_ */
