/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CallingSettings_calling.h
 *
 * Calling feature configuration for the business phone number
 */

#ifndef ONEMSG_SDK_MODEL_CallingSettings_calling_H_
#define ONEMSG_SDK_MODEL_CallingSettings_calling_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/model/CallingSettings_calling_audio.h"
#include "one-msg-sdk/model/CallingSettings_calling_sip.h"
#include "one-msg-sdk/model/CallingSettings_calling_video.h"
#include "one-msg-sdk/model/CallingSettings_calling_call_hours.h"
#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace sdk {
namespace model {



/// <summary>
/// Calling feature configuration for the business phone number
/// </summary>
class  CallingSettings_calling
    : public ModelBase
{
public:
    CallingSettings_calling();
    virtual ~CallingSettings_calling();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CallingSettings_calling members

    enum class StatusEnum
    {
        ENABLED,
        DISABLED,
    };
    /// <summary>
    /// Enable or disable Calling API on this number
    /// </summary>
    enum class Call_icon_visibilityEnum
    {
        DEFAULT,
        DISABLE_ALL,
    };
    /// <summary>
    /// Controls call icon visibility in the WhatsApp client
    /// </summary>
    enum class Callback_permission_statusEnum
    {
        ENABLED,
        DISABLED,
    };
    /// <summary>
    /// When ENABLED, a user who calls your business automatically grants call permission for business-initiated callbacks (subject to Meta rules). 
    /// </summary>
    enum class Srtp_key_exchange_protocolEnum
    {
        DTLS,
        SDES,
    };
    /// <summary>
    /// SRTP key exchange. DTLS is default/recommended. SDES is only valid when SIP signaling is enabled. 
    /// </summary>

    StatusEnum toStatusEnum(const utility::string_t& value) const;
    const utility::string_t fromStatusEnum(const StatusEnum value) const;


    Call_icon_visibilityEnum toCall_icon_visibilityEnum(const utility::string_t& value) const;
    const utility::string_t fromCall_icon_visibilityEnum(const Call_icon_visibilityEnum value) const;


    Callback_permission_statusEnum toCallback_permission_statusEnum(const utility::string_t& value) const;
    const utility::string_t fromCallback_permission_statusEnum(const Callback_permission_statusEnum value) const;


    Srtp_key_exchange_protocolEnum toSrtp_key_exchange_protocolEnum(const utility::string_t& value) const;
    const utility::string_t fromSrtp_key_exchange_protocolEnum(const Srtp_key_exchange_protocolEnum value) const;


    /// <summary>
    /// Enable or disable Calling API on this number
    /// </summary>
    StatusEnum getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const StatusEnum value);

    /// <summary>
    /// Controls call icon visibility in the WhatsApp client
    /// </summary>
    Call_icon_visibilityEnum getCallIconVisibility() const;
    bool callIconVisibilityIsSet() const;
    void unsetCall_icon_visibility();
    void setCallIconVisibility(const Call_icon_visibilityEnum value);

    /// <summary>
    /// When ENABLED, a user who calls your business automatically grants call permission for business-initiated callbacks (subject to Meta rules). 
    /// </summary>
    Callback_permission_statusEnum getCallbackPermissionStatus() const;
    bool callbackPermissionStatusIsSet() const;
    void unsetCallback_permission_status();
    void setCallbackPermissionStatus(const Callback_permission_statusEnum value);

    /// <summary>
    /// SRTP key exchange. DTLS is default/recommended. SDES is only valid when SIP signaling is enabled. 
    /// </summary>
    Srtp_key_exchange_protocolEnum getSrtpKeyExchangeProtocol() const;
    bool srtpKeyExchangeProtocolIsSet() const;
    void unsetSrtp_key_exchange_protocol();
    void setSrtpKeyExchangeProtocol(const Srtp_key_exchange_protocolEnum value);

    std::shared_ptr<CallingSettings_calling_call_hours> getCallHours() const;
    bool callHoursIsSet() const;
    void unsetCall_hours();
    void setCallHours(const std::shared_ptr<CallingSettings_calling_call_hours>& value);

    std::shared_ptr<CallingSettings_calling_sip> getSip() const;
    bool sipIsSet() const;
    void unsetSip();
    void setSip(const std::shared_ptr<CallingSettings_calling_sip>& value);

    std::shared_ptr<CallingSettings_calling_video> getVideo() const;
    bool videoIsSet() const;
    void unsetVideo();
    void setVideo(const std::shared_ptr<CallingSettings_calling_video>& value);

    std::shared_ptr<CallingSettings_calling_audio> getAudio() const;
    bool audioIsSet() const;
    void unsetAudio();
    void setAudio(const std::shared_ptr<CallingSettings_calling_audio>& value);

    /// <summary>
    /// Calling restrictions (response-only)
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<AnyType>> getRestrictions() const;
    bool restrictionsIsSet() const;
    void unsetRestrictions();
    void setRestrictions(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    /// <summary>
    /// Meta media IP ranges (response-only)
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<AnyType>> getIpAddresses() const;
    bool ipAddressesIsSet() const;
    void unsetIp_addresses();
    void setIpAddresses(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    /// <summary>
    /// Call icon country restrictions (response-only)
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<AnyType>> getCallIcons() const;
    bool callIconsIsSet() const;
    void unsetCall_icons();
    void setCallIcons(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    StatusEnum m_Status;
    bool m_StatusIsSet;

    Call_icon_visibilityEnum m_Call_icon_visibility;
    bool m_Call_icon_visibilityIsSet;

    Callback_permission_statusEnum m_Callback_permission_status;
    bool m_Callback_permission_statusIsSet;

    Srtp_key_exchange_protocolEnum m_Srtp_key_exchange_protocol;
    bool m_Srtp_key_exchange_protocolIsSet;

    std::shared_ptr<CallingSettings_calling_call_hours> m_Call_hours;
    bool m_Call_hoursIsSet;

    std::shared_ptr<CallingSettings_calling_sip> m_Sip;
    bool m_SipIsSet;

    std::shared_ptr<CallingSettings_calling_video> m_Video;
    bool m_VideoIsSet;

    std::shared_ptr<CallingSettings_calling_audio> m_Audio;
    bool m_AudioIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Restrictions;
    bool m_RestrictionsIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Ip_addresses;
    bool m_Ip_addressesIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Call_icons;
    bool m_Call_iconsIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_CallingSettings_calling_H_ */
