/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CallingSettings.h
 *
 * Calling settings payload for GET/POST &#x60;/callingSettings&#x60;. Proxies upstream &#x60;GET|POST /calling/settings&#x60;. Extra Meta fields may appear on GET responses; document core fields below. 
 */

#ifndef ONEMSG_SDK_MODEL_CallingSettings_H_
#define ONEMSG_SDK_MODEL_CallingSettings_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/model/CallingSettings_calling.h"
#include "one-msg-sdk/AnyType.h"
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace sdk {
namespace model {



/// <summary>
/// Calling settings payload for GET/POST &#x60;/callingSettings&#x60;. Proxies upstream &#x60;GET|POST /calling/settings&#x60;. Extra Meta fields may appear on GET responses; document core fields below. 
/// </summary>
class  CallingSettings
    : public ModelBase
{
public:
    CallingSettings();
    virtual ~CallingSettings();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CallingSettings members


    std::shared_ptr<CallingSettings_calling> getCalling() const;
    bool callingIsSet() const;
    void unsetCalling();
    void setCalling(const std::shared_ptr<CallingSettings_calling>& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    std::shared_ptr<CallingSettings_calling> m_Calling;
    bool m_CallingIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_CallingSettings_H_ */
