/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateReadMessage_request.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_CreateReadMessage_request_H_
#define ONEMSG_SDK_MODEL_CreateReadMessage_request_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace onemsg {
namespace sdk {
namespace model {



class  CreateReadMessage_request
    : public ModelBase
{
public:
    CreateReadMessage_request();
    virtual ~CreateReadMessage_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CreateReadMessage_request members


    utility::string_t getMessageId() const;
    bool messageIdIsSet() const;
    void unsetMessageId();
    void setMessageId(const utility::string_t& value);

    utility::string_t getMsgId() const;
    bool msgIdIsSet() const;
    void unsetMsgId();
    void setMsgId(const utility::string_t& value);

    /// <summary>
    /// Show WhatsApp typing indicator (max 25s or until reply)
    /// </summary>
    bool isTypingIndicator() const;
    bool typingIndicatorIsSet() const;
    void unsetTypingIndicator();
    void setTypingIndicator(bool value);


protected:
    utility::string_t m_MessageId;
    bool m_MessageIdIsSet;

    utility::string_t m_MsgId;
    bool m_MsgIdIsSet;

    bool m_TypingIndicator;
    bool m_TypingIndicatorIsSet;

};


}
}
}

#endif /* ONEMSG_SDK_MODEL_CreateReadMessage_request_H_ */
