/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetWebhook_200_response.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_GetWebhook_200_response_H_
#define ONEMSG_SDK_MODEL_GetWebhook_200_response_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace sdk {
namespace model {



class  GetWebhook_200_response
    : public ModelBase
{
public:
    GetWebhook_200_response();
    virtual ~GetWebhook_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetWebhook_200_response members


    utility::string_t getWebhookUrl() const;
    bool webhookUrlIsSet() const;
    void unsetWebhookUrl();
    void setWebhookUrl(const utility::string_t& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    utility::string_t m_WebhookUrl;
    bool m_WebhookUrlIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_GetWebhook_200_response_H_ */
