/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * InitiateCallResponse.h
 *
 * Successful call action response from upstream, returned as-is. On empty upstream body, 1msg may return &#x60;{ \&quot;result\&quot;: \&quot;success\&quot; }&#x60;. Upstream failures are often wrapped as HTTP 200 &#x60;{ \&quot;response\&quot;: { \&quot;error\&quot;: \&quot;...\&quot; } }&#x60;. 
 */

#ifndef ONEMSG_SDK_MODEL_InitiateCallResponse_H_
#define ONEMSG_SDK_MODEL_InitiateCallResponse_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/model/InitiateCallResponse_response.h"
#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>
#include "one-msg-sdk/model/InitiateCallResponse_calls_inner.h"
#include <vector>

namespace onemsg {
namespace sdk {
namespace model {



/// <summary>
/// Successful call action response from upstream, returned as-is. On empty upstream body, 1msg may return &#x60;{ \&quot;result\&quot;: \&quot;success\&quot; }&#x60;. Upstream failures are often wrapped as HTTP 200 &#x60;{ \&quot;response\&quot;: { \&quot;error\&quot;: \&quot;...\&quot; } }&#x60;. 
/// </summary>
class  InitiateCallResponse
    : public ModelBase
{
public:
    InitiateCallResponse();
    virtual ~InitiateCallResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// InitiateCallResponse members


    utility::string_t getMessagingProduct() const;
    bool messagingProductIsSet() const;
    void unsetMessaging_product();
    void setMessagingProduct(const utility::string_t& value);

    bool isSuccess() const;
    bool successIsSet() const;
    void unsetSuccess();
    void setSuccess(bool value);

    /// <summary>
    /// Present on outbound &#x60;connect&#x60; — contains the new call id
    /// </summary>
    std::vector<std::shared_ptr<InitiateCallResponse_calls_inner>> getCalls() const;
    bool callsIsSet() const;
    void unsetCalls();
    void setCalls(const std::vector<std::shared_ptr<InitiateCallResponse_calls_inner>>& value);

    /// <summary>
    /// Legacy success marker when upstream returns an empty body
    /// </summary>
    utility::string_t getResult() const;
    bool resultIsSet() const;
    void unsetResult();
    void setResult(const utility::string_t& value);

    std::shared_ptr<InitiateCallResponse_response> getResponse() const;
    bool responseIsSet() const;
    void unsetResponse();
    void setResponse(const std::shared_ptr<InitiateCallResponse_response>& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    utility::string_t m_Messaging_product;
    bool m_Messaging_productIsSet;

    bool m_Success;
    bool m_SuccessIsSet;

    std::vector<std::shared_ptr<InitiateCallResponse_calls_inner>> m_Calls;
    bool m_CallsIsSet;

    utility::string_t m_Result;
    bool m_ResultIsSet;

    std::shared_ptr<InitiateCallResponse_response> m_Response;
    bool m_ResponseIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_InitiateCallResponse_H_ */
