/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * InitiateCallRequest_session.h
 *
 * WebRTC SDP session (required for connect / pre_accept / accept)
 */

#ifndef ONEMSG_SDK_MODEL_InitiateCallRequest_session_H_
#define ONEMSG_SDK_MODEL_InitiateCallRequest_session_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace sdk {
namespace model {



/// <summary>
/// WebRTC SDP session (required for connect / pre_accept / accept)
/// </summary>
class  InitiateCallRequest_session
    : public ModelBase
{
public:
    InitiateCallRequest_session();
    virtual ~InitiateCallRequest_session();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// InitiateCallRequest_session members

    enum class Sdp_typeEnum
    {
        OFFER,
        ANSWER,
    };
    /// <summary>
    /// offer for outbound connect; answer for pre_accept/accept
    /// </summary>

    Sdp_typeEnum toSdp_typeEnum(const utility::string_t& value) const;
    const utility::string_t fromSdp_typeEnum(const Sdp_typeEnum value) const;


    /// <summary>
    /// offer for outbound connect; answer for pre_accept/accept
    /// </summary>
    Sdp_typeEnum getSdpType() const;
    bool sdpTypeIsSet() const;
    void unsetSdp_type();
    void setSdpType(const Sdp_typeEnum value);

    /// <summary>
    /// Full SDP (RFC 8866). Replace placeholders with SDP from your WebRTC stack. Must negotiate ICE, DTLS-SRTP, and OPUS for WhatsApp media. 
    /// </summary>
    utility::string_t getSdp() const;
    bool sdpIsSet() const;
    void unsetSdp();
    void setSdp(const utility::string_t& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    Sdp_typeEnum m_Sdp_type;
    bool m_Sdp_typeIsSet;

    utility::string_t m_Sdp;
    bool m_SdpIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_InitiateCallRequest_session_H_ */
