/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ListFlows_200_response.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_ListFlows_200_response_H_
#define ONEMSG_SDK_MODEL_ListFlows_200_response_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/AnyType.h"
#include <map>
#include <cpprest/json.h>
#include <vector>

namespace onemsg {
namespace sdk {
namespace model {



class  ListFlows_200_response
    : public ModelBase
{
public:
    ListFlows_200_response();
    virtual ~ListFlows_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ListFlows_200_response members


    std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> getItems() const;
    bool itemsIsSet() const;
    void unsetItems();
    void setItems(const std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getPaging() const;
    bool pagingIsSet() const;
    void unsetPaging();
    void setPaging(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    int32_t getCount() const;
    bool countIsSet() const;
    void unsetCount();
    void setCount(int32_t value);

    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();
    void setTotal(int32_t value);

    /// <summary>
    /// Error details returned by the provider. May be a string or a JSON object.
    /// </summary>
    std::shared_ptr<AnyType> getError() const;
    bool errorIsSet() const;
    void unsetError();
    void setError(const std::shared_ptr<AnyType>& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> m_Items;
    bool m_ItemsIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Paging;
    bool m_PagingIsSet;

    int32_t m_Count;
    bool m_CountIsSet;

    int32_t m_Total;
    bool m_TotalIsSet;

    boost::optional<std::shared_ptr<AnyType>> m_Error;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_ListFlows_200_response_H_ */
