/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ProfileInfo.h
 *
 * WhatsApp Business profile information
 */

#ifndef ONEMSG_CHAT_MODEL_ProfileInfo_H_
#define ONEMSG_CHAT_MODEL_ProfileInfo_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>
#include <vector>

namespace onemsg {
namespace chat {
namespace model {



/// <summary>
/// WhatsApp Business profile information
/// </summary>
class  ProfileInfo
    : public ModelBase
{
public:
    ProfileInfo();
    virtual ~ProfileInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ProfileInfo members

    enum class VerticalEnum
    {
        AUTOMOTIVE,
        BEAUTY_SPA_AND_SALON,
        CLOTHING_AND_APPAREL,
        EDUCATION,
        ENTERTAINMENT,
        EVENT_PLANNING_AND_SERVICE,
        FINANCE_AND_BANKING,
        FOOD_AND_GROCERY,
        PUBLIC_SERVICE,
        HOTEL_AND_LODGING,
        MEDICAL_AND_HEALTH,
        NON_PROFIT,
        PROFESSIONAL_SERVICES,
        SHOPPING_AND_RETAIL,
        TRAVEL_AND_TRANSPORTATION,
        RESTAURANT,
        OTHER,
    };
    /// <summary>
    /// Industry of the business
    /// </summary>

    VerticalEnum toVerticalEnum(const utility::string_t& value) const;
    const utility::string_t fromVerticalEnum(const VerticalEnum value) const;


    /// <summary>
    /// Profile&#39;s About section
    /// </summary>
    utility::string_t getAbout() const;
    bool aboutIsSet() const;
    void unsetAbout();
    void setAbout(const utility::string_t& value);

    /// <summary>
    /// Address of the business
    /// </summary>
    utility::string_t getAddress() const;
    bool addressIsSet() const;
    void unsetAddress();
    void setAddress(const utility::string_t& value);

    /// <summary>
    /// Description of the business
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    /// <summary>
    /// Business email
    /// </summary>
    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();
    void setEmail(const utility::string_t& value);

    /// <summary>
    /// Linked phone number
    /// </summary>
    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(const utility::string_t& value);

    /// <summary>
    /// Industry of the business
    /// </summary>
    VerticalEnum getVertical() const;
    bool verticalIsSet() const;
    void unsetVertical();
    void setVertical(const VerticalEnum value);

    /// <summary>
    /// Profile photo URL
    /// </summary>
    utility::string_t getPhoto() const;
    bool photoIsSet() const;
    void unsetPhoto();
    void setPhoto(const utility::string_t& value);

    std::vector<utility::string_t> getWebsites() const;
    bool websitesIsSet() const;
    void unsetWebsites();
    void setWebsites(const std::vector<utility::string_t>& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    utility::string_t m_About;
    bool m_AboutIsSet;

    utility::string_t m_Address;
    bool m_AddressIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    utility::string_t m_Email;
    bool m_EmailIsSet;

    utility::string_t m_Phone;
    bool m_PhoneIsSet;

    VerticalEnum m_Vertical;
    bool m_VerticalIsSet;

    utility::string_t m_Photo;
    bool m_PhotoIsSet;

    std::vector<utility::string_t> m_Websites;
    bool m_WebsitesIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_ProfileInfo_H_ */
