/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendList_request_sections_inner_rows_inner.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_SendList_request_sections_inner_rows_inner_H_
#define ONEMSG_SDK_MODEL_SendList_request_sections_inner_rows_inner_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace onemsg {
namespace sdk {
namespace model {



class  SendList_request_sections_inner_rows_inner
    : public ModelBase
{
public:
    SendList_request_sections_inner_rows_inner();
    virtual ~SendList_request_sections_inner_rows_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendList_request_sections_inner_rows_inner members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();
    void setTitle(const utility::string_t& value);

    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Title;
    bool m_TitleIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

};


}
}
}

#endif /* ONEMSG_SDK_MODEL_SendList_request_sections_inner_rows_inner_H_ */
