/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendContact_request_contacts_inner.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_SendContact_request_contacts_inner_H_
#define ONEMSG_SDK_MODEL_SendContact_request_contacts_inner_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/model/SendContact_request_contacts_inner_org.h"
#include "one-msg-sdk/model/SendContact_request_contacts_inner_name.h"
#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <vector>
#include "one-msg-sdk/model/SendContact_request_contacts_inner_phones_inner.h"

namespace onemsg {
namespace sdk {
namespace model {

class SendContact_request_contacts_inner_name;
class SendContact_request_contacts_inner_org;
class SendContact_request_contacts_inner_phones_inner;


class  SendContact_request_contacts_inner
    : public ModelBase
{
public:
    SendContact_request_contacts_inner();
    virtual ~SendContact_request_contacts_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendContact_request_contacts_inner members


    std::shared_ptr<SendContact_request_contacts_inner_name> getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const std::shared_ptr<SendContact_request_contacts_inner_name>& value);

    utility::string_t getBirthday() const;
    bool birthdayIsSet() const;
    void unsetBirthday();
    void setBirthday(const utility::string_t& value);

    std::vector<std::shared_ptr<AnyType>> getAddresses() const;
    bool addressesIsSet() const;
    void unsetAddresses();
    void setAddresses(const std::vector<std::shared_ptr<AnyType>>& value);

    std::vector<std::shared_ptr<AnyType>> getEmails() const;
    bool emailsIsSet() const;
    void unsetEmails();
    void setEmails(const std::vector<std::shared_ptr<AnyType>>& value);

    std::shared_ptr<SendContact_request_contacts_inner_org> getOrg() const;
    bool orgIsSet() const;
    void unsetOrg();
    void setOrg(const std::shared_ptr<SendContact_request_contacts_inner_org>& value);

    std::vector<std::shared_ptr<SendContact_request_contacts_inner_phones_inner>> getPhones() const;
    bool phonesIsSet() const;
    void unsetPhones();
    void setPhones(const std::vector<std::shared_ptr<SendContact_request_contacts_inner_phones_inner>>& value);

    std::vector<std::shared_ptr<AnyType>> getUrls() const;
    bool urlsIsSet() const;
    void unsetUrls();
    void setUrls(const std::vector<std::shared_ptr<AnyType>>& value);


protected:
    std::shared_ptr<SendContact_request_contacts_inner_name> m_Name;
    bool m_NameIsSet;

    utility::string_t m_Birthday;
    bool m_BirthdayIsSet;

    std::vector<std::shared_ptr<AnyType>> m_Addresses;
    bool m_AddressesIsSet;

    std::vector<std::shared_ptr<AnyType>> m_Emails;
    bool m_EmailsIsSet;

    std::shared_ptr<SendContact_request_contacts_inner_org> m_Org;
    bool m_OrgIsSet;

    std::vector<std::shared_ptr<SendContact_request_contacts_inner_phones_inner>> m_Phones;
    bool m_PhonesIsSet;

    std::vector<std::shared_ptr<AnyType>> m_Urls;
    bool m_UrlsIsSet;

};


}
}
}

#endif /* ONEMSG_SDK_MODEL_SendContact_request_contacts_inner_H_ */
