/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendContact_request_contacts_inner_name.h
 *
 * 
 */

#ifndef ONEMSG_CHAT_MODEL_SendContact_request_contacts_inner_name_H_
#define ONEMSG_CHAT_MODEL_SendContact_request_contacts_inner_name_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace onemsg {
namespace chat {
namespace model {



class  SendContact_request_contacts_inner_name
    : public ModelBase
{
public:
    SendContact_request_contacts_inner_name();
    virtual ~SendContact_request_contacts_inner_name();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendContact_request_contacts_inner_name members


    utility::string_t getFormattedName() const;
    bool formattedNameIsSet() const;
    void unsetFormatted_name();
    void setFormattedName(const utility::string_t& value);

    utility::string_t getFirstName() const;
    bool firstNameIsSet() const;
    void unsetFirst_name();
    void setFirstName(const utility::string_t& value);

    utility::string_t getLastName() const;
    bool lastNameIsSet() const;
    void unsetLast_name();
    void setLastName(const utility::string_t& value);

    utility::string_t getMiddleName() const;
    bool middleNameIsSet() const;
    void unsetMiddle_name();
    void setMiddleName(const utility::string_t& value);

    utility::string_t getSuffix() const;
    bool suffixIsSet() const;
    void unsetSuffix();
    void setSuffix(const utility::string_t& value);

    utility::string_t getPrefix() const;
    bool prefixIsSet() const;
    void unsetPrefix();
    void setPrefix(const utility::string_t& value);


protected:
    utility::string_t m_Formatted_name;
    bool m_Formatted_nameIsSet;

    utility::string_t m_First_name;
    bool m_First_nameIsSet;

    utility::string_t m_Last_name;
    bool m_Last_nameIsSet;

    utility::string_t m_Middle_name;
    bool m_Middle_nameIsSet;

    utility::string_t m_Suffix;
    bool m_SuffixIsSet;

    utility::string_t m_Prefix;
    bool m_PrefixIsSet;

};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_SendContact_request_contacts_inner_name_H_ */
