/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendContact_request.h
 *
 * 
 */

#ifndef ONEMSG_CHAT_MODEL_SendContact_request_H_
#define ONEMSG_CHAT_MODEL_SendContact_request_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/model/SendContact_request_contacts_inner.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace onemsg {
namespace chat {
namespace model {

class SendContact_request_contacts_inner;


class  SendContact_request
    : public ModelBase
{
public:
    SendContact_request();
    virtual ~SendContact_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendContact_request members


    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(const utility::string_t& value);

    std::vector<std::shared_ptr<SendContact_request_contacts_inner>> getContacts() const;
    bool contactsIsSet() const;
    void unsetContacts();
    void setContacts(const std::vector<std::shared_ptr<SendContact_request_contacts_inner>>& value);


protected:
    utility::string_t m_Phone;
    bool m_PhoneIsSet;

    std::vector<std::shared_ptr<SendContact_request_contacts_inner>> m_Contacts;
    bool m_ContactsIsSet;

};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_SendContact_request_H_ */
