/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendContact_request_contacts_inner_org.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_SendContact_request_contacts_inner_org_H_
#define ONEMSG_SDK_MODEL_SendContact_request_contacts_inner_org_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace onemsg {
namespace sdk {
namespace model {



class  SendContact_request_contacts_inner_org
    : public ModelBase
{
public:
    SendContact_request_contacts_inner_org();
    virtual ~SendContact_request_contacts_inner_org();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendContact_request_contacts_inner_org members


    utility::string_t getCompany() const;
    bool companyIsSet() const;
    void unsetCompany();
    void setCompany(const utility::string_t& value);

    utility::string_t getDepartment() const;
    bool departmentIsSet() const;
    void unsetDepartment();
    void setDepartment(const utility::string_t& value);

    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();
    void setTitle(const utility::string_t& value);


protected:
    utility::string_t m_Company;
    bool m_CompanyIsSet;

    utility::string_t m_Department;
    bool m_DepartmentIsSet;

    utility::string_t m_Title;
    bool m_TitleIsSet;

};


}
}
}

#endif /* ONEMSG_SDK_MODEL_SendContact_request_contacts_inner_org_H_ */
