/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendPaymentRequest_request.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_SendPaymentRequest_request_H_
#define ONEMSG_SDK_MODEL_SendPaymentRequest_request_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include "one-msg-sdk/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace sdk {
namespace model {



class  SendPaymentRequest_request
    : public ModelBase
{
public:
    SendPaymentRequest_request();
    virtual ~SendPaymentRequest_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendPaymentRequest_request members

    enum class RegionEnum
    {
        IN,
        SG,
        BR,
    };

    RegionEnum toRegionEnum(const utility::string_t& value) const;
    const utility::string_t fromRegionEnum(const RegionEnum value) const;


    int32_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(int32_t value);

    RegionEnum getRegion() const;
    bool regionIsSet() const;
    void unsetRegion();
    void setRegion(const RegionEnum value);

    utility::string_t getBody() const;
    bool bodyIsSet() const;
    void unsetBody();
    void setBody(const utility::string_t& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getInteractive() const;
    bool interactiveIsSet() const;
    void unsetInteractive();
    void setInteractive(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);

    std::map<utility::string_t, std::shared_ptr<AnyType>> getAction() const;
    bool actionIsSet() const;
    void unsetAction();
    void setAction(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    int32_t m_Phone;
    bool m_PhoneIsSet;

    RegionEnum m_Region;
    bool m_RegionIsSet;

    utility::string_t m_Body;
    bool m_BodyIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Interactive;
    bool m_InteractiveIsSet;

    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Action;
    bool m_ActionIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_SDK_MODEL_SendPaymentRequest_request_H_ */
