/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendLocation_request_1.h
 *
 * 
 */

#ifndef ONEMSG_SDK_MODEL_SendLocation_request_1_H_
#define ONEMSG_SDK_MODEL_SendLocation_request_1_H_

#include <boost/optional.hpp>

#include "one-msg-sdk/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace onemsg {
namespace sdk {
namespace model {



class  SendLocation_request_1
    : public ModelBase
{
public:
    SendLocation_request_1();
    virtual ~SendLocation_request_1();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendLocation_request_1 members


    utility::string_t getLat() const;
    bool latIsSet() const;
    void unsetLat();
    void setLat(const utility::string_t& value);

    utility::string_t getLng() const;
    bool lngIsSet() const;
    void unsetLng();
    void setLng(const utility::string_t& value);

    utility::string_t getAddress() const;
    bool addressIsSet() const;
    void unsetAddress();
    void setAddress(const utility::string_t& value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getQuotedMsgId() const;
    bool quotedMsgIdIsSet() const;
    void unsetQuotedMsgId();
    void setQuotedMsgId(const utility::string_t& value);

    utility::string_t getChatId() const;
    bool chatIdIsSet() const;
    void unsetChatId();
    void setChatId(const utility::string_t& value);

    int32_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(int32_t value);


protected:
    utility::string_t m_Lat;
    bool m_LatIsSet;

    utility::string_t m_Lng;
    bool m_LngIsSet;

    utility::string_t m_Address;
    bool m_AddressIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_QuotedMsgId;
    bool m_QuotedMsgIdIsSet;

    utility::string_t m_ChatId;
    bool m_ChatIdIsSet;

    int32_t m_Phone;
    bool m_PhoneIsSet;

};


}
}
}

#endif /* ONEMSG_SDK_MODEL_SendLocation_request_1_H_ */
