/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnyType.h
 *
 * This is the implementation of an any JSON type.
 */

#ifndef ONEMSG_SDK_MODEL_AnyType_H_
#define ONEMSG_SDK_MODEL_AnyType_H_


#include "one-msg-sdk/Object.h"

#include <cpprest/details/basic_types.h>
#include <cpprest/json.h>

namespace onemsg {
namespace sdk {
namespace model {

class  AnyType : public Object {
public:
  AnyType();
  virtual ~AnyType();

  /////////////////////////////////////////////
  /// ModelBase overrides
  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

private:
  web::json::value m_value;
};

}
}
}

#endif /* ONEMSG_SDK_MODEL_AnyType_H_ */
