/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetCommerce_200_response_inner.h
 *
 * 
 */

#ifndef ONEMSG_CHAT_MODEL_GetCommerce_200_response_inner_H_
#define ONEMSG_CHAT_MODEL_GetCommerce_200_response_inner_H_

#include <boost/optional.hpp>

#include "one-msg-chat-api/ModelBase.h"

#include "one-msg-chat-api/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace chat {
namespace model {



class  GetCommerce_200_response_inner
    : public ModelBase
{
public:
    GetCommerce_200_response_inner();
    virtual ~GetCommerce_200_response_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetCommerce_200_response_inner members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    bool isIsCartEnabled() const;
    bool isCartEnabledIsSet() const;
    void unsetIs_cart_enabled();
    void setIsCartEnabled(bool value);

    bool isIsCatalogVisible() const;
    bool isCatalogVisibleIsSet() const;
    void unsetIs_catalog_visible();
    void setIsCatalogVisible(bool value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    bool m_Is_cart_enabled;
    bool m_Is_cart_enabledIsSet;

    bool m_Is_catalog_visible;
    bool m_Is_catalog_visibleIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_GetCommerce_200_response_inner_H_ */
