/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MessageSentResponse.h
 *
 * Response for successfully sent message
 */

#ifndef ONEMSG_CHAT_MODEL_MessageSentResponse_H_
#define ONEMSG_CHAT_MODEL_MessageSentResponse_H_

#include <boost/optional.hpp>

#include "one-msg-chat-api/ModelBase.h"

#include "one-msg-chat-api/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>
#include <cpprest/json.h>

namespace onemsg {
namespace chat {
namespace model {



/// <summary>
/// Response for successfully sent message
/// </summary>
class  MessageSentResponse
    : public ModelBase
{
public:
    MessageSentResponse();
    virtual ~MessageSentResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MessageSentResponse members


    /// <summary>
    /// Whether the message was successfully queued for sending
    /// </summary>
    bool isSent() const;
    bool sentIsSet() const;
    void unsetSent();
    void setSent(bool value);

    /// <summary>
    /// Message ID
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    /// <summary>
    /// Status message
    /// </summary>
    utility::string_t getMessage() const;
    bool messageIsSet() const;
    void unsetMessage();
    void setMessage(const utility::string_t& value);

    /// <summary>
    /// Detailed description
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);


    /// <summary>
    /// Get additional properties (properties not defined in the schema)
    /// </summary>
    std::map<utility::string_t, web::json::value> getAdditionalProperties() const;
    bool additionalPropertiesIsSet() const;
    void unsetAdditionalProperties();
    /// <summary>
    /// Set additional properties
    /// </summary>
    void setAdditionalProperties(const std::map<utility::string_t, web::json::value>& value);
    /// <summary>
    /// Add a single additional property
    /// </summary>
    void addAdditionalProperty(const utility::string_t& key, const web::json::value& value);

protected:
    bool m_Sent;
    bool m_SentIsSet;

    utility::string_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Message;
    bool m_MessageIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    std::map<utility::string_t, web::json::value> m_AdditionalProperties;
    bool m_AdditionalPropertiesIsSet;
};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_MessageSentResponse_H_ */
