/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendFlow_request_1.h
 *
 * 
 */

#ifndef ONEMSG_CHAT_MODEL_SendFlow_request_1_H_
#define ONEMSG_CHAT_MODEL_SendFlow_request_1_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "one-msg-chat-api/ModelBase.h"

#include "one-msg-chat-api/Object.h"
#include <cpprest/details/basic_types.h>
#include "one-msg-chat-api/model/SendFlow_request_1_header.h"

namespace onemsg {
namespace chat {
namespace model {



class  SendFlow_request_1
    : public ModelBase
{
public:
    SendFlow_request_1();
    virtual ~SendFlow_request_1();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendFlow_request_1 members

    enum class FlowActionEnum
    {
        NAVIGATE,
        DATA_EXCHANGE,
    };
    enum class ModeEnum
    {
        DRAFT,
        PUBLISHED,
    };

    FlowActionEnum toFlowActionEnum(const utility::string_t& value) const;
    const utility::string_t fromFlowActionEnum(const FlowActionEnum value) const;


    ModeEnum toModeEnum(const utility::string_t& value) const;
    const utility::string_t fromModeEnum(const ModeEnum value) const;


    utility::string_t getBody() const;
    bool bodyIsSet() const;
    void unsetBody();
    void setBody(const utility::string_t& value);

    std::shared_ptr<SendFlow_request_1_header> getHeader() const;
    bool headerIsSet() const;
    void unsetHeader();
    void setHeader(const std::shared_ptr<SendFlow_request_1_header>& value);

    utility::string_t getFooter() const;
    bool footerIsSet() const;
    void unsetFooter();
    void setFooter(const utility::string_t& value);

    utility::string_t getFlowId() const;
    bool flowIdIsSet() const;
    void unsetFlowId();
    void setFlowId(const utility::string_t& value);

    utility::string_t getFlowToken() const;
    bool flowTokenIsSet() const;
    void unsetFlowToken();
    void setFlowToken(const utility::string_t& value);

    utility::string_t getFlowCta() const;
    bool flowCtaIsSet() const;
    void unsetFlowCta();
    void setFlowCta(const utility::string_t& value);

    FlowActionEnum getFlowAction() const;
    bool flowActionIsSet() const;
    void unsetFlowAction();
    void setFlowAction(const FlowActionEnum value);

    std::shared_ptr<Object> getFlowActionPayload() const;
    bool flowActionPayloadIsSet() const;
    void unsetFlowActionPayload();
    void setFlowActionPayload(const std::shared_ptr<Object>& value);

    utility::string_t getFlowMessageVersion() const;
    bool flowMessageVersionIsSet() const;
    void unsetFlowMessageVersion();
    void setFlowMessageVersion(const utility::string_t& value);

    ModeEnum getMode() const;
    bool modeIsSet() const;
    void unsetMode();
    void setMode(const ModeEnum value);

    std::shared_ptr<Object> getFlowActionData() const;
    bool flowActionDataIsSet() const;
    void unsetFlowActionData();
    void setFlowActionData(const std::shared_ptr<Object>& value);

    utility::string_t getFlowActionScreen() const;
    bool flowActionScreenIsSet() const;
    void unsetFlowActionScreen();
    void setFlowActionScreen(const utility::string_t& value);

    utility::string_t getQuotedMsgId() const;
    bool quotedMsgIdIsSet() const;
    void unsetQuotedMsgId();
    void setQuotedMsgId(const utility::string_t& value);

    utility::string_t getChatId() const;
    bool chatIdIsSet() const;
    void unsetChatId();
    void setChatId(const utility::string_t& value);

    int32_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(int32_t value);


protected:
    utility::string_t m_Body;
    bool m_BodyIsSet;

    std::shared_ptr<SendFlow_request_1_header> m_Header;
    bool m_HeaderIsSet;

    utility::string_t m_Footer;
    bool m_FooterIsSet;

    utility::string_t m_FlowId;
    bool m_FlowIdIsSet;

    utility::string_t m_FlowToken;
    bool m_FlowTokenIsSet;

    utility::string_t m_FlowCta;
    bool m_FlowCtaIsSet;

    FlowActionEnum m_FlowAction;
    bool m_FlowActionIsSet;

    std::shared_ptr<Object> m_FlowActionPayload;
    bool m_FlowActionPayloadIsSet;

    utility::string_t m_FlowMessageVersion;
    bool m_FlowMessageVersionIsSet;

    ModeEnum m_Mode;
    bool m_ModeIsSet;

    std::shared_ptr<Object> m_FlowActionData;
    bool m_FlowActionDataIsSet;

    utility::string_t m_FlowActionScreen;
    bool m_FlowActionScreenIsSet;

    utility::string_t m_QuotedMsgId;
    bool m_QuotedMsgIdIsSet;

    utility::string_t m_ChatId;
    bool m_ChatIdIsSet;

    int32_t m_Phone;
    bool m_PhoneIsSet;

};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_SendFlow_request_1_H_ */
