/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendContact_request_contacts_inner_phones_inner.h
 *
 * 
 */

#ifndef ONEMSG_CHAT_MODEL_SendContact_request_contacts_inner_phones_inner_H_
#define ONEMSG_CHAT_MODEL_SendContact_request_contacts_inner_phones_inner_H_

#include <boost/optional.hpp>

#include "one-msg-chat-api/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace onemsg {
namespace chat {
namespace model {



class  SendContact_request_contacts_inner_phones_inner
    : public ModelBase
{
public:
    SendContact_request_contacts_inner_phones_inner();
    virtual ~SendContact_request_contacts_inner_phones_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendContact_request_contacts_inner_phones_inner members


    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(const utility::string_t& value);

    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const utility::string_t& value);

    utility::string_t getWaId() const;
    bool waIdIsSet() const;
    void unsetWa_id();
    void setWaId(const utility::string_t& value);


protected:
    utility::string_t m_Phone;
    bool m_PhoneIsSet;

    utility::string_t m_Type;
    bool m_TypeIsSet;

    utility::string_t m_Wa_id;
    bool m_Wa_idIsSet;

};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_SendContact_request_contacts_inner_phones_inner_H_ */
