/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.22.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SetWhatsappBusinessEncryption_request.h
 *
 * 
 */

#ifndef ONEMSG_CHAT_MODEL_SetWhatsappBusinessEncryption_request_H_
#define ONEMSG_CHAT_MODEL_SetWhatsappBusinessEncryption_request_H_

#include <boost/optional.hpp>

#include "one-msg-chat-api/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace onemsg {
namespace chat {
namespace model {



class  SetWhatsappBusinessEncryption_request
    : public ModelBase
{
public:
    SetWhatsappBusinessEncryption_request();
    virtual ~SetWhatsappBusinessEncryption_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SetWhatsappBusinessEncryption_request members


    /// <summary>
    /// 2048-bit RSA public key in PEM format
    /// </summary>
    utility::string_t getBusinessPublicKey() const;
    bool businessPublicKeyIsSet() const;
    void unsetBusiness_public_key();
    void setBusinessPublicKey(const utility::string_t& value);


protected:
    utility::string_t m_Business_public_key;
    bool m_Business_public_keyIsSet;

};


}
}
}

#endif /* ONEMSG_CHAT_MODEL_SetWhatsappBusinessEncryption_request_H_ */
